### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by opranda** [TeamNewPipe/NewPipe#11191]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

When I click play, the video loads and the message "Network error" appears and nothing happens

## Exception
* User Action: play stream
* Request: Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=GnUCGS0KRqM
* Content Country: RU
* Content Language: ru-RU
* App Language: ru_RU
* Service: YouTube
* Version: 0.27.0
* OS: Linux Android 5.1 - 22
<details><summary><b>Crash log </b></summary><p>

com.google.android.exoplayer2.ExoPlaybackException: Source error
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:194)
 at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
 at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
 at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
 at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
 at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
 at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
 at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:818)

</details>
<hr>

**Comment by MDP43140** [comment]
Did you try different video, on different device or network? I got this problem too where it stuck buffering no matter what quality or video/audio playback, it persists in Firefox, yt-dlp (i use Seal) and many other 3rd party apps, I can only watch said content on YouTube mobile or Chromium-based browsers

**Comment by Baltazar500** [comment]
The same story. Android 5.1, 0.27.0, error 403 - forbidden

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=s1f7-slwbeo
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 5.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>

I passed the NewPipe request through the debug proxy and repeated the request to 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false' with all headers via curl. The resulting 'itag' streams (mp4/webm/etc) return "403 forbidden".

```

HTTP/1.1 403 Forbidden
Last-Modified: Wed, 02 May 2007 10:26:10 GMT
Content-Type: text/plain
Content-Length: 0
Connection: close
Vary: Origin
Cross-Origin-Resource-Policy: cross-origin
X-Content-Type-Options: nosniff
Date: Sat, 22 Jun 2024 19:56:26 GMT
Server: gvs 1.0

```

yt-dlp algorithms receive working links to streams

**Comment by MingMing0000** [comment]
I have the same issue, also android 5.1. SoundCloud works fine it's just youtube that suddenly doesn't work

**Comment by iiD4x** [comment]
Same issue, android 5.1

**Comment by RadenAmzar** [comment]
Is there any solution for this issue?

**Comment by Baltazar500** [comment]
The problem is gone 0_o Videos are playing again

**Comment by nash268** [comment]
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=pM_rvWwQoqU
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Realme/RMX1821/RMX1821:10/QP1A.190711.020/1624873154:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:227)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by tag27** [comment]
The strangest thing in my case is that, at first, I didn't have this problem, but from about two~three days ago until now it appears from time to time. But I notice that it's more frequent in case I use pip mode or when I put the video in the background. 

OS: Android 12, One UI 4.1
Device: Samsung Galaxy A11 (SM-A115M/DS)

**Comment by Baltazar500** [comment]
@tag27, Maybe YouTube is reconfiguring its servers? After the 22nd format was removed https://github.com/yt-dlp/yt-dlp/issues/10206 NewPipe worked fine. There are no problems at the moment. Perhaps you have a "forbidden/403" format in pip at the moment? Try changing the quality

**Comment by A-Nicoladie** [comment]
Hi ! I have the same issue on some videos (YT). Videos depends on the day... 


## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=N8hibUNfENA
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

**Comment by nash268** [comment]
for me when error occurs it's always at 00:59 time stamp.

**Comment by nash268** [comment]
It seems to have solved the issue after changing my DNS to Quad9. previously i was using google dns.
Needs more testing

**Comment by rjdg14** [comment]
In my experience this issue seems to either occur on random videos about a minute in, or when skipping to a later segment of random videos. It maybe occurs on about every fifth or so video.

**Comment by NoahJelen** [comment]
Could this have something to do with how NewPipe is making the requests to YouTube's servers (something with cookies maybe)? I noticed this error disappears for a while if I kill NewPipe and clear its cache.

**Comment by krushia** [comment]
Confirming that:

1. The first part of a video will play before the error occurs
2. After the error, the triggering video will no longer play at all
3. After the first occurance, there appears to be an increased probability of triggering the error with other videos (but they may still play okay)
4. Restarting NewPipe usually fixes it
5. It happens sporadically

**Comment by 1xFF** [comment]
Many users are reporting a 403 at around one minute of playback, these issues are being marked as duplicates of this issue. However this issue has significant differences in both the steps to reproduce and traceback line numbers. It's possible that these are seperate issues.

**Comment by tag27** [comment]
> Many users are reporting a 403 at around one minute of playback, these issues are being marked as duplicates of this issue. However this issue has significant differences in both the steps to reproduce and traceback line numbers. It's possible that these are seperate issues.

I believe it's the same thing, because possibly the OP of this Issue didn't notice that the video paused before completing 1 minute. I hadn't realized it myself when I commented earlier.

**Comment by acarasimon96** [comment]
> YouTube Music uploads (the ones that are just album art rather than an actual video) don't seem to trigger it either, maybe they use a different format that doesn't have the same problems?

In my experience, both normal and YouTube Music videos are affected; I get the same exact behavior on either kind.

**Comment by NoahJelen** [comment]
> > YouTube Music uploads (the ones that are just album art rather than an actual video) don't seem to trigger it either, maybe they use a different format that doesn't have the same problems?
> 
> In my experience, both normal and YouTube Music videos are affected; I get the same exact behavior on either kind.

My issue actually happens more with music than it does for regular videos. When I watch videos normally, the issues happens less in my experience.

**Comment by NoahJelen** [comment]
I have an idea for a workaround: Make a PR that causes NewPipe to automatically wipe the metadata cache and begin replaying the video from wherever it left off at every time this error occurs since wiping the metadata cache (in Settings -> History and Cache -> Wipe Cached Metadata) seems to make this issue go away temporarily.

**Comment by Khang-NT** [comment]
YouTube did a massive breaking change on the player js (`WEB` client), to reproduce on Chrome, just set up a proxy app (Charles, ProxyMan,...) and map YouTube player js to this URL:
```
https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
```

**Comment by uacnix** [comment]
It might be connected to the latest Google's tricks with vp9 stream, to make youtube less stable on anything other than Chrome:
https://www.ghacks.net/2024/06/19/google-disrupted-youtube-video-playback-on-firefox-again/
https://bugzilla.mozilla.org/show_bug.cgi?id=1878510
Symptoms look the same - I use NP mostly for music in traffic, and I've noticed that some videos (be it either YT Music ones or some totally random, normal videos, not even marked as music) have the same issues- playing first few seconds, then "Network error" and skipping to the next video in playlist. If I try to go back and skip to the part after the issue, it still wont work and requires me to force kill the app.

**Comment by TechnologyClassroom** [comment]
I said this in one of the other linked threads: Google seems to be A/B testing a number of things recently. SponsorBlock noted that one of those things is server-side ad injection which is changing the length of the videos.

**Comment by alliethebanana** [comment]
So this may or may not be helpful.
Around the time I started being unable to play videos through Newpipe, I went to my smart TV instead to try to stream videos through SmartTube beta, and lo and behold, now there is a 403 error code whenever it tries buffering the videos.

So it could be as some people have mentioned in the thread that Google is experimenting with things server side to block requests from adblocking clients

**Comment by ACR-Jeff** [comment]
The only thing I can get working is other apps that utilize the invidious instances, Everything else just fails

**Comment by nash268** [comment]
update **0.27.1** has fixed this issue for me, atleast error hasn't occurred in 24 hours after the update.

This update was fix for a new different error.[[FIXED IN 0.27.1][YouTube] HTTP error 403 when starting videos](https://github.com/TeamNewPipe/NewPipe/issues/11255#issue-2398629565)

**Comment by rjdg14** [comment]
While 0.27.1 fixes the issue with videos not loading at all, the issue in this thread remains, and I've also encountered an increase in this version with videos occasionally not loading at all (but without an error; they just hang) or taking several minutes to buffer before they are playable. 0.27.1 does seem noticeably less fast than previous versions of NewPipe.

**Comment by synctext** [comment]
Updating to 0.27.1 helps!
Also still getting this error regularly. Running on latest Android, Google phone. Restarting Newpipe indeed fixes playback issues. Hope this helps.

**Comment by opranda** [comment]
The update solved the problem
Thanks!

**Comment by rigmo** [comment]
Great news. I run agin pipe. Temporary I use revanced but I do not like it.

**Comment by tuxayo** [comment]
> The only thing I can get working is other apps that utilize the invidious instances, Everything else just fails

Just tried with PipePipe and v3.5.1 seems to have fixed the issue:
https://codeberg.org/NullPointerException/PipePipeClient/commit/13f5c3b11c868f70996d63dcbba0ecfb215f9997
https://codeberg.org/NullPointerException/PipePipeExtractor/commit/e68d5a49073f97718078c4517f59b0e4261f2838

Testing:
- found a problematic video on NewPipe
- tried on PipePipe v3.5.0 => fails around the 1 minute mark
- retried on PipePipe v3.5.1 => works (as advertised in the changelog)

full commit history in case I missed a relevant change:
https://codeberg.org/NullPointerException/PipePipeClient/commits/branch/dev
https://codeberg.org/NullPointerException/PipePipeExtractor/commits/branch/main

**Comment by godfuture** [comment]
This error happens quite often for me. A video randomly stops playing. After the error appeared, the video can not be continued.

Very annoying. LibreTube seems more stable.

LineageOS 20
NewPipe 0.27.1

**Comment by Gamonte** [comment]
I've never had this problem until after I updated NewPipe to 0.27.1.
The video works up to the 00:59 minute mark and stops at 01:00.

Android 14
NewPipe 0.27.1

**Comment by alvinlaw2** [comment]
Yes the issue wasnt fixed in this new version. Because this issue of video stops at 0:59 was happening to version 0.27.0 as well. Except in version 0.27.0 it gotten worse because eventually all videos couldnt play.

**Comment by ale5000-git** [comment]
I wonder if this fix may apply also to NewPipe: https://github.com/yt-dlp/yt-dlp/pull/10456

**Comment by frere-jacques** [comment]
It seems like resetting the cache of the app can help to get it working again.

**Comment by gstr3745** [comment]
Hi,
I don't know if it could be useful to someone, but this is what I experienced about this issue:
- If I'm on my mobile network, everything seems to work fine
- If I'm on my local network (WiFi or VPN) it randomly gets stuck: I've got AdguardHome networkwide, with quad9 dns
- When a video is stuck, marking it as already seen and then playing it again sometimes works

I have no technical capabilities to investigate this bug further, I'm afraid :(

e/Os/ V2.1-t
NewPipe 0.27.1

**Comment by kirxkirx** [comment]
This seems to be a very typical error occuring while I'm driving and using NewPipe through a mobile connection. The playback stops with this error and doesn't resume even after pressing Play again. This doesn't happen with the official player in similar conditions. It would be great if NewPipe tries more aggressively to recover from a network error like this one, possibly caused by a temporary loss of connection.


## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=87X8-NIQUVc
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>
