### ISSUE TITLE
Fastlane per-release changelogs are too long

### ISSUE THREAD

**Issue by IzzySoft** [TeamNewPipe/NewPipe#12815]
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

n/a

### Steps to reproduce the bug

From our monthly report:

* build/org.schabi.newpipe/metadata/cs/changelogs/1005.txt has 622 chars
* build/org.schabi.newpipe/metadata/fr/changelogs/1005.txt has 703 chars
* build/org.schabi.newpipe/metadata/hi/changelogs/1005.txt has 596 chars
* build/org.schabi.newpipe/metadata/hu/changelogs/1005.txt has 624 chars
* build/org.schabi.newpipe/metadata/it/changelogs/1005.txt has 656 chars
* build/org.schabi.newpipe/metadata/pa/changelogs/1005.txt has 603 chars
* build/org.schabi.newpipe/metadata/sk/changelogs/1005.txt has 621 chars
* build/org.schabi.newpipe/metadata/uk/changelogs/1005.txt has 650 chars

### Expected behavior

all changelogs are within the 500 char limit according to the fastlane specs

### Actual behavior

changelogs exceeding the limit

**Comment by IzzySoft** [comment]
I've removed them now at our end (tired of the returning warnings 🙈). Btw, Weblate allows you to define limits for the string length, you might consider enforcing them there. Specs say max 500 chars for each changelog file.

**Comment by TobiGr** [comment]
Thank you for reporting this.. Weblate enforced this limit previously. I'll have to dive into Weblate error messages once again 🎉 

I tried to mark the check to be enforced, but was greeted by this error message:

> Es gibt mehr als eine Datei für die Sprache Norwegisch (Bokmål): fastlane/metadata/android/nb_NO, fastlane/metadata/android/nb-NO Bitte passen Sie die Dateimaske an und verwenden Sie Komponenten für die Übersetzung verschiedener Ressourcen.

There is only the [nb-NO]([nb-NO](https://github.com/TeamNewPipe/NewPipe/tree/dev/fastlane/metadata/android/nb-NO)) directory ...

**Comment by TobiGr** [comment]
the max-length check is now displayed as enforced check in the weblate interface. However, I am not quite sure if it is actually enforced. We'll have to see.

**Comment by IzzySoft** [comment]
Thanks, @TobiGr! In the past, it was a warning one could override (and unfortunately, many did). Recently, they've added enforcement. For reference, see e.g. https://github.com/Crazy-Marvin/VacationDays/issues/309#issuecomment-3677945236

**Comment by TobiGr** [comment]
yeah, that's what I enabled. I was still able to submit translations which exceeded the limit after that.

**Comment by IzzySoft** [comment]
Honestly? That was supposed to be fixed by a recent patch, which by now should have been deployed. IIRC it was even Sylvia herself who wrote the PR for that.

**Comment by TobiGr** [comment]
I corrected the file sizes by hand for the next release and will monitor if weblate enforces the changes in the future

**Comment by IzzySoft** [comment]
Thanks a lot! If you want to: [this Github action](https://github.com/ashutoshgngwr/validate-fastlane-supply-metadata) can keep an eye on it for you 😉

**Comment by IzzySoft** [comment]
Problem is back btw, @TobiGr 

* build/org.schabi.newpipe/metadata/fr/changelogs/1009.txt has 555 chars
* build/org.schabi.newpipe/metadata/sk/changelogs/1009.txt has 534 chars
* build/org.schabi.newpipe/metadata/ta/changelogs/1009.txt has 596 chars

again, I've simply removed those (so they fall back to the completely shown en-US).
