### ISSUE TITLE
Audio only player pops up when connected to bluetooth device

### ISSUE THREAD

**Issue by xNS5** [TeamNewPipe/NewPipe#1596]
**Device**: Samsung Galaxy S8+
**OS**: Latest update
**Newpipe Version**: Latest build

**Issue**: Whenever I connect to my car's bluetooth radio, the newpipe audio only player pops up as if it were my default media player (which it isn't). 

I've tried clearing defaults, clearing cache, and everything I could think of.

**Comment by theScrabi** [comment]
Yea thats a known bug.

**Comment by Offerel** [comment]
Is there some workaround for that issue?

**Comment by Rorschach1010** [comment]
Same here. Whenever I used Newpipe (after my default audio player) and get into my car, it doesn't start my audio player but newpipe and obviously, there is no music starting. I have to force close newpipe and start my default player. I'm running Android 10 btw.

Seeing that this is a pretty old bug, are there plans to get this fixed any time soon or as @Offerel asked, is there some kind of workaround?

**Comment by Stypox** [comment]
Does #3178 fix this issue? Could you test the apk provided there?

**Comment by Rorschach1010** [comment]
> Does #3178 fix this issue? Could you test the apk provided there?

hmm... seems like the download link expired. I'll ask in #3178 if someone can share it.

**Comment by opusforlife2** [comment]
_Probably_ fixed by #2907.

**Comment by Stypox** [comment]
@xNS5 @Offerel @Rorschach1010 could you test [this apk](https://github.com/TeamNewPipe/NewPipe/files/5012955/app-debug.zip) (from https://github.com/TeamNewPipe/NewPipe/pull/3178#issuecomment-667724810 )

**Comment by Offerel** [comment]
At least by testing with a headphone it works.

**Comment by xNS5** [comment]
I don't use newpipe anymore because the issue was persisting, however I've installed Newpipe on my phone to see if the issue has been resolved. I'll do some testing tomorrow as well!

**Comment by Offerel** [comment]
It's me again. Re-test with car audio successfully. Hopefully this will be in the next release.

**Comment by xNS5** [comment]
Just following up. I tested it a bit and I'm unable to replicate the issue. It appears to have been resolved!

**Comment by Haxaaaa** [comment]
I have the same problem: Whenever I connect to my car's bluetooth radio, the newpipe audio only player pops up.
Phone: Samsung Note10+

**Comment by Offerel** [comment]
It seems this fix is not in the release as of yet. At least with the current version from f-droid and also GitHub the situation isn't fixed.

That's the main reason why I didn't use this app anymore.

Hopefully this will change in the upcoming future, since the app itself is really nice, but this react to Bluetooth is annoying as hell.

**Comment by Offerel** [comment]
@Haxaaaa I have made a new test after giving up the last times. At least with the F-Droid version it seems to work now. I have not imported anything and setup all from scratch. This time i enabled both options for external Video AND external Audio player (before that, i had only external Audio Player enabled). Since i switched both of these options to enabled, it seems to fix the popup, when i connect it to my BT Car audio system. I have no idea if this is the secret, but i thought, i give it a new try.
