### ISSUE TITLE
Reciever not registered

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1641]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

This crash happens when leaving the main player via any hardware button except "home" after adjusting volume or brightness.

Related: #1604, #1635

## Exception
* __User Action:__ Play stream
* __Request:__ play stream
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.13.7
* __OS:__ Linux Android 4.2.1 - 17 | 6.0 - 23

```
java.lang.IllegalArgumentException: Receiver not registered: org.schabi.newpipe.player.BasePlayer$1@4270e3f0
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:657)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1411)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:445)
	at org.schabi.newpipe.player.BasePlayer.unregisterBroadcastReceiver(BasePlayer.java:367)
	at org.schabi.newpipe.player.BasePlayer.destroy(BasePlayer.java:295)
	at org.schabi.newpipe.player.VideoPlayer.destroy(VideoPlayer.java:542)
	at org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:234)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1211)
	at android.app.Activity.performStop(Activity.java:5264)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3583)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3642)
	at android.app.ActivityThread.access$1200(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by mauriciocolli** [comment]
This is happening because we are [destroying the player `onPause`](https://github.com/TeamNewPipe/NewPipe/blob/bf05ff6048a524a9ca32c0699dcdf723776259d9/app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java#L234), and when `onResume` is called later, the broadcast receiver is not being registered anymore (this only happens in the player object `<init>`). It leads to some other bugs in features that rely on this being properly registered (pause when the audio output is disconnected, for example). [This change](https://github.com/TeamNewPipe/NewPipe/commit/98c65fb9b73d94a85c53c928cf019dfab8231eda#diff-d45c9b9532307e47fd7c4399ebcead8bR368) is what causing the crash itself.

I'll include a fix in my next PR that I mentioned in the other issue.

**Comment by theScrabi** [comment]
@mauriciocolli how long would that fix take? I wanted to release v0.14.0 within the next 2 or 3 days.

**Comment by theScrabi** [comment]
Nvm I fixed it :)

**Comment by mauriciocolli** [comment]
@theScrabi https://github.com/TeamNewPipe/NewPipe/commit/6e382c64a4e8d18b724b94bf331bc1f9a6db1bb0 doesn't fix the issue that I described.

**Comment by theScrabi** [comment]
I see, but I asume this issue existed before, so it's not a regression.

**Comment by mauriciocolli** [comment]
Why not fix it before releasing? Even more so as it was a very simple issue to fix...

I'll push it tonight.

**Comment by theScrabi** [comment]
ok
