### ISSUE TITLE
Downloads not always being deleted

### ISSUE THREAD

**Issue by kasbah** [TeamNewPipe/NewPipe#1655]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hi, my downloads are not always being deleted. The undo prompt comes up and they disappear but then often they re-appear when I re-open the downloads menu.

The app has storage permissions. I also disabled the Lineage OS privacy guard and that seemed to make it less likely to happen (but it still happened once). 

I am running Lineage OS 14.1-20180623-NIGHTLY-i9300 on a Samsung Galaxy S3 (GT-I9300).  NewPipe is 0.13.7 from F-Droid.

**Comment by theScrabi** [comment]
That might happen when you leave the activitiy without the popup to disapear.

**Comment by theScrabi** [comment]
Maybe we should delete on leave without waiting for the popup to disapear. @somethingweirdhere what do u think?

**Comment by Somethingweirdhere** [comment]
@theScrabi Yeah, I think it should be that way. For me, the popup disappears anyways when I leave Downloads, so there is no reason to wait any further.

**Comment by r1c4rd0** [comment]
I get the same problem and it's even worse when i try to delete a few videos one after the other because then all the deleted videos after the first just restore the previously deleted videos.

Also, if I delete a video that failed to download and try to download it again, then i get two instances of the video and both try to download again. Thrice if it fails again and I try to again.

**Comment by TobiGr** [comment]
fixed in #1759

**Comment by beastwick** [comment]
@TobiGr Is there something special one must do besides upgrading to the newest version? I am on the original Pixel with the most up to date version of the app, but this is still an issue for me.

**Comment by r1c4rd0** [comment]
I don't know if it was fixed, but in the latest release that I can download(v0.14.2) I'm still having the issue.

**Comment by gkeegan** [comment]
Compile the app in Android studio after cloning the repository. The current apk in releases doesn't have the newest features. 

Once 14.3 is released it will most likely have this issue fixed, along with many other things fixed/added. (Probably more themes, viewing comments, fixed video loading at video start [this is less likely], and some other things.)
