### ISSUE TITLE
Deleting Files 3 times but they never get deleted... 

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#1793]
Maybe this is a phone problem but it was not before.

In the downloads section i press delete, all okay the song dissapears but then if i continue deleting songa, the deleted reappear again and actually they never get deleted from the memory :'(

**Comment by theScrabi** [comment]
Could you make a video of the deletion pls

**Comment by goxr3plus** [comment]
Yes. I will.

**Comment by nachoparker** [comment]
I can verify this. In order to really delete the file I have to hit back several times until I have completely exited the app.

Otherwise, the fail is not really deleted and shows up again next time you go to downloads

thanks!

**Comment by goxr3plus** [comment]
@nachoparker  Exactly my friend :) , couldn't send a real pick of it , like should make a short gif.

**Comment by theScrabi** [comment]
It's the snakbar, it seems not to work, so lets get rid of it again.

**Comment by theScrabi** [comment]
Help welcome :)

**Comment by TobiGr** [comment]
IIRC this has been fixed in #1759.

**Comment by nachoparker** [comment]
I forgot to mention something else. If you delete the downloaded files externally, for instance, from VLC, this doesn't get detected by NewPipe and the files still show in the downloads section.

**Comment by theScrabi** [comment]
Yea thats because there is an internal database that holds a reference to the files. One might have to write an updater that checks if the file still exists.

**Comment by nachoparker** [comment]
thank you very much
