### ISSUE TITLE
Lag when video plays in background.

### ISSUE THREAD

**Issue by EnriUnagi** [TeamNewPipe/NewPipe#2170]
The app severally lags when playing a video in the background making it very difficult to do anything while it's playing. I'm using Android 8.1 btw.

**Comment by theScrabi** [comment]
Confirmed. I know the issue i hate it as well, and I said it need to be fixed but someone has to do it.

Th issue is the timestamp update in the notification. It should be removed.

**Comment by ronidee** [comment]
On my device, some videos do not cause UI lag while playing in background. 

One of them is Cheat Codes - SEX (https://www.youtube.com/watch?v=OORoOGY8D2M)

My device: Honor 9 lite, los 15.1, newpipe 16.1

Why is that??? 🤔

**Comment by SebiderSushi** [comment]
The pull request has been merged into the newly released version 0.16.2 so this should be fixed. I'm using Arch btw.

**Comment by ronidee** [comment]
Just wanted to report that I just installed 0.16.2 and this issue is still present.
(My device, look above) 

`Debian sid`

**Comment by MohamedKiouaz** [comment]
Hi,

Same here, J7 2017 with Android 8.1.0.
It's almost not possible to use New Pipe while playing a video in background.
I am listening to [this long music video](https://www.youtube.com/watch?v=snRZHMqnItA) and it triggers the bug sill in 0.16.2.

Thanks for the hard work guys. It's an awesome

**Comment by EnriUnagi** [comment]
Yeah this issue is still present, hope it gets resolved soon. Best of luck!

**Comment by expobar** [comment]
Can confirm. 0.16.2 still has this issue. 
Worse case: the app almost freezes once I am few videos deep while background is playing.
Normal times: the app is laggy while background is playing. 

It's very rare that I trigger the app to almost freeze, once it does 'clear cache' fixes it most of the time.
