### ISSUE TITLE
[Bug] Links in description open twice

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2526]
I've observed this behavior in v0.16.2 and v0.17.0

This isn't easily noticeable in regular use because you're normally loading a new activity after tapping a link. If you tap a link then cancel the opening of it, you will see a second dialog box reveal itself from behind the first.

Steps to reproduce:

- Click any description link
- Click outside the 'open in' dialog
- First dialog closes while second remains open

**Comment by Stypox** [comment]
Confirmed

**Comment by allendema** [comment]
Cannot reproduce with 0.19.8.

**Comment by Stypox** [comment]
I can't reproduce, either. Can you @Gymcap confirm this has been fixed?

**Comment by opusforlife2** [comment]
I remember testing this and seeing two Open With dialogues, one behind the other revealed on a back press. Just tested and this is gone for me now. We'll reopen if Gymcap can confirm it still exists.

**Comment by Gymcap** [comment]
Sorry for disappearing, can confirm this is fixed on my end
