### ISSUE TITLE
Crash report email bounced - wrong address

### ISSUE THREAD

**Issue by kuba-orlik** [TeamNewPipe/NewPipe#3040]
After sending a crash report, it bounced, saying:

```
<crashreport@newpipe.schabi.org>: host [...]
    said: 530 5.7.0 Must issue a STARTTLS command first (in reply to MAIL FROM
    command)
```

**Comment by iah** [comment]
I got the same issue:

This is the mail system at host mxtls1.mailbox.org.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                             The mail system

<crashreport@newpipe.schabi.org>: Cannot start TLS: handshake failure

**Comment by saepurusass** [comment]
The problem is simple:
`mail.commandnotfound.org` refuses to accept mail without encryption - should it reject plaintext email is a long debate. I think plaintext email should be blocked - but that is not up to me to decide.

Your SENDING server can not negotiate TLS connection because it does not support modern TLS protocols and/or ciphers and then eventually goes to fallback mode, which is plaintext (no encryption at all). And `mail.commandnotfound.org` refuses to accept that.
So in the end sending of message fails.

There is no issue connecting to mail.commandnotfound.org using TLS
Following is done on quite old Ubuntu 16.04 using libssl 1.0.2g.
Most production servers should use much newer packages.
When testing it on MODERN system, it even connects using TLSv1.3 - so mail.commandnotfound.org is up to date and uses modern and SECURE protocols/ciphers.
It is the SENDING server, that needs attention. It should be updated to allow modern TLS protocols and ciphers. After that everything will work.
```
# openssl s_client -starttls smtp -crlf -connect mail.commandnotfound.org:25
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = mail.orange-it.de
verify return:1
---
Certificate chain
 0 s:/CN=mail.orange-it.de
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHXzCCBkegAwIBAgISBD4EMpBAhdU6C0YuoXs0CPPvMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTEyMjMwOTA2MjdaFw0y
MDAzMjIwOTA2MjdaMBwxGjAYBgNVBAMTEW1haWwub3JhbmdlLWl0LmRlMIICIjAN
BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0qEjkvhhoazsX8+b9XmWDjnN6eJp
TS6WdW338GFn5VJNeSiz03BVm6qB8zSE6btCr/RZYzFHnfHqSsQjDTGNcul6fsFy
gCvZMGxXG9gU6fam2jwIEjhomQLRtvfQFRl6R5B9yldFP0IgHziAnR9N9FF39rC1
EAioy5W6qV6gD03mN2juhD5Uc9jTNNkC6zVDrNL8eNbrLXHkJeDnxj37ossiP4DH
gRm7fpwwpJGqu9Jsl1qvMLVxF5qPC3LatUtUHqEMKWu/310sq3O8mlLAjBjYm+8n
5LTKWum9SaeT5YLWRHTBosFbKojuO08Wzz7Rt5PA8o4VKKMShZmIkfEGagzv0juz
hi711NTkRsX2d6W/XRVNSInJt9+UiNcGRFLR5haBXYovFcqDwGvSr40c6hqxnpLH
QbaBQH8gXawM30OzMQjtoOmO+IzGQrL29chnQThUoL8KonFLRMxR1T4gRXaEuJV7
O5fOucd8GJeDhRFrab//xSblgDGaV8E+xG1RoGtsmBumIOkqsSWxqzE17qAGPq54
AMlthhCDL3TcTRsjKF6futFdflyM1P4nfP5v4tn2LrbqHQvBH/eRQw4exPdp86eg
8pMAotxDn0/v+l+8JldR+W2//XdNiHUbJhwHIGwL9euI/Z1xEUnyLAelfF9bxAFM
SXtGVthksZE/W5MCAwEAAaOCA2swggNnMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUE
FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
0Uxu9avbN5PTDbue2jfgTvWo1VIwHwYDVR0jBBgwFoAUqEpqYwR93brm0Tm3pkVl
7/Oo7KEwbwYIKwYBBQUHAQEEYzBhMC4GCCsGAQUFBzABhiJodHRwOi8vb2NzcC5p
bnQteDMubGV0c2VuY3J5cHQub3JnMC8GCCsGAQUFBzAChiNodHRwOi8vY2VydC5p
bnQteDMubGV0c2VuY3J5cHQub3JnLzCCAR4GA1UdEQSCARUwggERghNjb21tYW5k
bm90Zm91bmQub3JnghhpbWFwLmNvbW1hbmRub3Rmb3VuZC5vcmeCEWltYXAub3Jh
bmdlLWl0LmRlghhtYWlsLmNvbW1hbmRub3Rmb3VuZC5vcmeCEW1haWwub3Jhbmdl
LWl0LmRlghZteC5jb21tYW5kbm90Zm91bmQub3Jngg9teC5vcmFuZ2UtaXQuZGWC
DG9yYW5nZS1pdC5kZYIXcG9wLmNvbW1hbmRub3Rmb3VuZC5vcmeCEHBvcC5vcmFu
Z2UtaXQuZGWCGHBvcDMuY29tbWFuZG5vdGZvdW5kLm9yZ4IRcG9wMy5vcmFuZ2Ut
aXQuZGWCEXNtdHAub3JhbmdlLWl0LmRlMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcG
CysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5
cHQub3JnMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYAXqdz+d9WwOe1Nkh90Eng
MnqRmgyEoRIShBh1loFxRVgAAAFvMjjm1AAABAMARzBFAiAeauqCey7QHcH65c1/
sYkmxkuTNuVw7Op8fEP3S1C8SQIhAIa0Wyq7RCM/E43t43yNrS8Dkph6hF7XEFow
2wGELJr1AHcAB7dcG+V9aP/xsMYdIxXHuuZXfFeUt2ruvGE6GmnTohwAAAFvMjjn
AwAABAMASDBGAiEA2TBGqE0x4XrVcpAu+/xim5PoITQ0IzINv+LpXGJwtloCIQDZ
MBYqNc1FEfFFAf11rc10Wu9B1daoCV7xI4GhdgDcPDANBgkqhkiG9w0BAQsFAAOC
AQEAHZISKiM0+/5B1L0pZ4YjuhRc0mzxAc2G6YWkeLXAuHjcvMDIJfRmIEHc75uE
HdhsGA3CjRh9MPcs1Hf/e+3gNnwJgv8Uj02bk0Yo53Fu86JSU9XJeB8Bznms8DFW
vlH/X5H1VZ9CZTNmCLpK7KpW3K3a6CG0GapliivHQK3gJLZ6J3G+VMKUi95/07Jm
RGpbKU6+x+4EFaZ9CY4xsfnMNdeaIpVppT1/J0+/0zDXDf8wclxAnNRnGTdGvrzZ
BPbEb+MmTAHaHoMAM3QTk4giwaYZFKw98VAtbix9AfMZQOmcwFlowNk21qp8COEh
Wk5X7dQwOEsVOUjxiEnpcGWsOg==
-----END CERTIFICATE-----
subject=/CN=mail.orange-it.de
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4204 bytes and written 474 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: BCC616DA5D3BBF75953BA9597225F5A2AA3D01F1015DF2C2C65FFD2204C27B61
    Session-ID-ctx: 
    Master-Key: E06823466CADFCD99428445CF66D5866E6A82820D6E5EC21693A6F30F3D16032E801BB7CA694A58F1DA9F54D62381E37
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 0d d3 e6 c6 95 74 35 9d-a5 6a 47 44 e5 79 2e 34   .....t5..jGD.y.4
    0010 - bd 5e 77 97 25 c8 f1 8f-73 34 61 07 2b 71 c1 e8   .^w.%...s4a.+q..
    0020 - 44 ad fb 48 dc fe 37 d6-19 50 49 d6 b8 d5 44 d9   D..H..7..PI...D.
    0030 - 65 c0 02 5c 79 63 2e e2-13 2e 3b 7f c9 7f 43 ec   e..\yc....;...C.
    0040 - 01 4f cb b4 90 e4 78 b2-00 83 9f 91 19 e6 79 3e   .O....x.......y>
    0050 - af fc d9 38 21 d4 fc eb-30 88 cc 0d 65 52 ba 80   ...8!...0...eR..
    0060 - a4 c9 2d f4 87 eb f5 97-75 26 e3 16 77 73 e7 c5   ..-.....u&..ws..
    0070 - 07 b9 27 fa 78 db cb 9d-e0 43 bd 42 04 a9 2a a2   ..'.x....C.B..*.
    0080 - 3b 9f 0b 5b fd 2e b4 37-3c bc 8e b4 e9 d7 72 f3   ;..[...7<.....r.
    0090 - fa 6b 98 59 41 af 6f 41-9a ac 1a 19 90 09 15 2e   .k.YA.oA........

    Start Time: 1580469402
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
250 DSN
```

**Comment by TheAssassin** [comment]
Thanks for your explanation @saepurusass. The mail system enforces encryption. Unencrypted mail traffic has been a security nightmare ever since, and this issue has been solved literally decades ago by the introduction of SSL/TLS encryption.

@kuba-orlik the server has *never* responded with any message that would indicate the address was wrong, the message has told you exactly the same as we did...

@iah you should file an issue with your provider, mailbox.org should really support up to date crypto...

Closing as resolved.

By the way, the mail system has been aching the last couple days from tens of thousands of mails regarding the latest YouTube induced issues. Please just upgrade to 0.18.2 or later first.

**Comment by jhoc2000** [comment]
I've just started getting the same message after updating to 0.18.2. I've been able to send error reports before this and my mail server has not changed.

**Comment by jhoc2000** [comment]
This is still happening. It was not happening before and I have not changed my mail account settings. In fact I have checked my settings and they have STARTTLS set for sending mail. You need to look at what you have changed to cause this to happen please. 

Here is the bounce attachment:


Reporting-MTA: dns; icp-osb-irony-out6.external.iinet.net.au

Final-Recipient: rfc822;crashreport@newpipe.schabi.org
Action: failed
Status: 5.0.0 (permanent failure)
Remote-MTA: dns; [88.99.208.206]
Diagnostic-Code: smtp; 5.1.0 - Unknown address error 530-'5.7.0 Must issue a STARTTLS command first' (delivery attempts: 0)

**Comment by TheAssassin** [comment]
@jhoc2000 your mail server clearly does not support TLS for transport between mail servers. This is hilarious, we got 2020, not 2000.

For everyone who might think this issue should be reopened:

***This is not a bug and therefore will not be fixed.*** It's on *your* mail server to finally ***encrypt*** your outgoing mail traffic!

I'm not willing to reduce the overall security just to accept mails from outdated and unmaintained mail servers. It is in *your* interest that the request is denied, after all! We're preventing clear text data transfers. It should not be necessary for our server to reject your server's traffic. Please ask yourself, *why is my mail server actually even trying to send my mails in cleartext?*

I've been really, really, really patient with other people's mail servers and only enforced own outgoing traffic to be encrypted. But at some point I had to finally enforce incoming traffic as well.

I actually would like to also block any sorts of google mail, they're the worst, but at least their traffic is encrypted. If the vast majority of NewPipe traffic only didn't use GMail...

**Comment by Poolitzer** [comment]
Deep breaths.
