### ISSUE TITLE
Crash / strange behaviour when opening closed play queue from recent apps 

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3200]
- [x] I checked if the issue/feature exists in the latest version.

- Play an audio in the background player.
- Back out of the app entirely.
- Open the Background Player by tapping the notification.
- Back out of it.
- Stop the video from the notification.
- Try to open the player from Recents.

**Comment by Stypox** [comment]
I did not understand what the problem is :sweat_smile:

**Comment by wb9688** [comment]
Could confirm.

@Stypox: See this video: [recording_20200308_172127.mp4.zip](https://github.com/TeamNewPipe/NewPipe/files/4303496/recording_20200308_172127.mp4.zip)

**Comment by opusforlife2** [comment]
Whoa. _Crash_ if you try the same thing with the popup player.

Attempt to invoke virtual method something.something.getRootView() on a null object reference.

**Comment by PeterHindes** [comment]
This might also be related to a minor issue i was having. Some launchers like [niagara](https://play.google.com/store/apps/details?id=bitpit.launcher&hl=en_US), have a built in widget for music players. However when you tap to open the associated app, it cant find newpipe.

**Comment by opusforlife2** [comment]
Still exists on 0.19.8.

**Comment by Stypox** [comment]
Fixed in unified player / notification improvements (I just tested on Android 7.0, reopen if I'm wrong)

**Comment by opusforlife2** [comment]
Still happening for me. If you're trying on your Huawei, maybe that handles it differently?

**Comment by opusforlife2** [comment]
Basically, the app should either:
- remove the background/popup player queue activity from Recents when the stream is killed from the notification, or
- open Newpipe's main activity instead

One example of something similar happening is when you have App Info open for any app, and you delete the app through Play Store or F-Droid, Android removes the App Info activity from Recents as well, because there is no app whose information can be shown anymore.

**Comment by Stypox** [comment]
Oh yeah, I am on Huawei and it open Newpipe's main activity

**Comment by opusforlife2** [comment]
> I did not understand what the problem is 😅

No wonder, then. xD
