### ISSUE TITLE
No audio controls

### ISSUE THREAD

**Issue by fajis1** [TeamNewPipe/NewPipe#3864]
On the latest release of Android 11R. There are no audio controls when I select play in the background. There is also no way to get into the background audio playlist if your adding more things to it. 

See the picture to understand. 

![Screenshot_20200708-165709](https://user-images.githubusercontent.com/68034464/86974540-27506480-c13c-11ea-8388-3e0f41fa7379.png)

This is what it should look like. 

![Screenshot_20200708-165706](https://user-images.githubusercontent.com/68034464/86974528-21f31a00-c13c-11ea-9aa9-1994ff588710.png)

**Comment by wb9688** [comment]
Is that fixed in #3178?

**Comment by fajis1** [comment]
> Is that fixed in #3178?

I do not think so. I have the latest version installed, and just installed the beta version from an hour ago. The issue still persists. 

I am on the Android  11 beta, and the latest version that I installed today changed the way they do media controls. They are not grouped in one tab. Not sure what the issue is, but I am guessing its brand new because of the new Android beta 11. 

I have a similar issue with using newpipe on chrome OS. Sending the video to background doesn't work correctly there either. I don't remember if it doesn't play at all. But the controls to stop and to control the playlist don't work.

**Comment by Stypox** [comment]
@fajis1 #3178 should implement the standard Android notification, so if "Podcast Addict" works, that version of NewPipe should work, too. Could you try an apk provided there?

**Comment by fajis1** [comment]
@Stypox just tried to download that apk, but was told that "Firefox send" us down while they make improvements.

**Comment by Stypox** [comment]
@fajis1 sorry if I wasn't clear enough. Donwload the apk in the latest comment: https://github.com/TeamNewPipe/NewPipe/pull/3178#issuecomment-629225675

**Comment by fajis1** [comment]
@Stypox that apk does work.

**Comment by Stypox** [comment]
Great! Notification improvements will hopefully land in 0.20.0
