### ISSUE TITLE
Website Parse Error with v0.19.8

### ISSUE THREAD

**Issue by atdocboy** [TeamNewPipe/NewPipe#3992]
There seems to be some website parse error specific to some videos. 
I attach the error log here. Interestingly, most other videos work fine.

------------------------------------------------
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=qQ99wbHnrAI
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.19.8
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by wb9688** [comment]
Use v0.19.8.

**Comment by atdocboy** [comment]
I am using the latest version (0.19.8)

**Comment by wb9688** [comment]
Oh, sorry, I didn't look at the error itself, but thought this was yet another duplicate.

**Comment by atdocboy** [comment]
The error seems to be have been resolved. No clue why?
Closing the issue for now.

**Comment by wb9688** [comment]
It hasn't been fixed yet, but sometimes NewPipe doesn't seem to error (though it still won't actually play it then).

**Comment by pedrud** [comment]
I'm getting this same error on all videos. Although, I'm on 0.19.8.

**Comment by wb9688** [comment]
@pedrud: Could you confirm that https://www.youtube.com/watch?v=oDMlKOKr9bA does not work? That's a video that should definitely work.

If it doesn't work, could you install https://wb9688.stackstorage.com/s/eBfTmrxPUsGTNGAx, connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue using that video, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then I might be able to fix this issue.

**Comment by fabianski7** [comment]
> If it doesn't work, could you install https://wb9688.stackstorage.com/s/eBfTmrxPUsGTNGAx

this version is working perfectly, the one in f-droid isn't.

**Comment by Stypox** [comment]
@fabianski7 the one in fdroid is still outdated, update to 0.19.8

**Comment by dessalines** [comment]
Do yall have your own fdroid repository? F-droid updates come wayyy too slow for this.

**Comment by Stypox** [comment]
Yes, here it is: https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/

**Comment by dessalines** [comment]
Hrm... its showing 0 apps, even after an update.

**Comment by TobiGr** [comment]
@dessalines Please remove it and add it again: https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/ 
I was stupid and used http instead of https in the qr code. it is fixed now.

**Comment by dessalines** [comment]
Haha no probs. Looks good now, thanks!

**Comment by 5cientist** [comment]
Even , every videos shows error
![Screenshot_20200731-011229](https://user-images.githubusercontent.com/14964705/88967327-2aeb8d00-d29d-11ea-86ef-1b2ffd035034.jpg)

**Comment by Stypox** [comment]
@5cientist update to 0.19.8

**Comment by 5cientist** [comment]
> @5cientist update to 0.19.8

Thanks it works now ! , But fdroid still suggest old version need to update in fdroid too...
![Screenshot_20200731-014324](https://user-images.githubusercontent.com/14964705/88970161-743ddb80-d2a1-11ea-8d05-f9b476c085ed.jpg)

**Comment by opusforlife2** [comment]
@TobiGr From the blog post:
> The easiest way to add the repository is to scan the QR code below or **click this link** if you’re viewing this on your device already.

This clickable link needs to be updated as well. It autofills an HTTP instead of HTTPS link in the F-Droid dialogue.

**Comment by opusforlife2** [comment]
I'm pretty sure this is a duplicate of #3336 as well. The video link in the OP plays now.
