### ISSUE TITLE
NewPipe v0.19.8 Not showing comments

### ISSUE THREAD

**Issue by GitterDoneBoi** [TeamNewPipe/NewPipe#4001]
Issue: NewPipe doesn't display comments on any video. This is as of version 0.19.8. Since it hasn't been brought up by anyone yet I'm assuming it's a isolated case, but it's odd nonetheless. I'm on a Poco F1 running MIUI 11(Android 10). 

I'll take up the last paragraph on a thank you note. Seriously, you guys are absolutely amazing! I only play music in NewPipe, satisfy my inner data hoarder with NewPipe, most of my viewing is done on NewPipe. It's freaking awesome that I'm able to experience all this, for absolutely zero costs! And the quick response to the changes Google made upstream is a great sign that I can get behind. Cheers to every dev on this project, you are a huge part of my digital life :)

**Comment by GitterDoneBoi** [comment]
![Screenshot_2020-07-29-09-37-20-500_org schabi newpipe](https://user-images.githubusercontent.com/67357310/88758000-0bf9d780-d185-11ea-879c-ea7a06993dd5.jpg)
This is newpipe

**Comment by GitterDoneBoi** [comment]
![Screenshot_2020-07-29-09-38-03-052_com vanced android youtube](https://user-images.githubusercontent.com/67357310/88758025-1c11b700-d185-11ea-875f-5e2b1d7782e3.jpg)
And YouTube Vanced for comparison

**Comment by gkeegan** [comment]
Please ensure you have comments enabled in the settings.

**Comment by wb9688** [comment]
@gkeegan: If that was the case, there also wasn't a "No comments".

@GitterDoneBoi: Do you always have this for all videos? Could you please press Settings -> History & cache -> Wipe cached metadata and try a few videos? If it's not for all videos, it's a known issue that sometimes it fails to load.

**Comment by GitterDoneBoi** [comment]
@gkeegan I do have comments enabled, hence the existence of a comment page

**Comment by GitterDoneBoi** [comment]
@wb9688 I just tried this, no luck though. It's still the same for every video.

**Comment by wb9688** [comment]
Could you install a https://wb9688.stackstorage.com/s/eBfTmrxPUsGTNGAx, connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then I might be able to fix this issue.

**Comment by GitterDoneBoi** [comment]
![Wha](https://user-images.githubusercontent.com/67357310/88767045-b29aa400-d196-11ea-9981-8731f488099a.jpg)
That's...odd. The debug version works perfectly fine.

**Comment by GitterDoneBoi** [comment]
@wb9688 Update: Reinstalling NewPipe did the trick, but I think I have narrowed down to the problem. When I opened the fresh app, everything worked fine but when I imported this backup of my settings everything reverted back to the problem state.

Here is the backup in question

[Problem zip](https://drive.google.com/file/d/1-5DD1e0bbTRo3qxGlbXx5IUXgUeFlD08/view?usp=drivesdk)

**Comment by GitterDoneBoi** [comment]
The problem is fixed now btw so I still appreciate you providing the debug to help me fix it faster :) thanks!

**Comment by vdbhb59** [comment]
Actually it is still the same. I tried clean install too. Still does not work. Back to the old. Does not play anything at all. No matter what I do. Tried in 5 different phones, and on 2 android TV. Download too does not work.
0.19.8 FDroid version.

**Comment by aand18** [comment]
I had comments and 80% of videos not running ("video unavailable") . 

I uninstalled and reinstalled. For some reason my settings/subscriptions were untouched. It worked when I cleared "data". I'm not sure why "data" doesn't get cancelled when uninstalling. 

This fixed the comments and the 80% if videos that wouldn't run. 

But after changing the settings (download location, default resolution, restricted content etc.) it turned back to comments not working and also many videos failing.

**Comment by aand18** [comment]
I think I've narrowed it down to "YouTube restricted mode" in the Content settings. Disabling this makes everything work. BTW, what does it do?

**Comment by wb9688** [comment]
>For some reason my settings/subscriptions were untouched. It worked when I cleared "data". I'm not sure why "data" doesn't get cancelled when uninstalling.

@aand18: That's not possible, unless you didn't actually uninstall or your device's Android is buggy.

>I think I've narrowed it down to "YouTube restricted mode" in the Content settings. Disabling this makes everything work. BTW, what does it do?

Enable YouTube's restricted mode, so that you can't watch inappropriate videos.

**Comment by aand18** [comment]
> > For some reason my settings/subscriptions were untouched. It worked when I cleared "data". I'm not sure why "data" doesn't get cancelled when uninstalling.
> 
> @aand18: That's not possible, unless you didn't actually uninstall or your device's Android is buggy.

It's a vanilla Samsung S8...might be bugged 🤷‍♂️ . All I know is it happened before with NewPipe, I had to uninstall the F-Droid variant to be able to install the GitHub release - all my settings were kept. 

> > I think I've narrowed it down to "YouTube restricted mode" in the Content settings. Disabling this makes everything work. BTW, what does it do?
> 
> Enable YouTube's restricted mode, so that you can't watch inappropriate videos.

Maybe "YouTube restricted mode" was broken before v0.19.8. Anyway, it makes sense, restricted blocks only some videos and all comments.

BTW "YouTube restricted mode" deserves a clearer name. Like "Restrict mature content"...

**Comment by wb9688** [comment]
@aand18: There was no such setting before it was added and it's disabled by default in NewPipe. The other (broken) setting that existed was "Age restricted content", which will show an error for 18+ videos if that's disabled, but it has been fixed now. I do think "YouTube restricted mode" is a clear name, as YouTube calls that feature "Restricted Mode", see https://support.google.com/youtube/answer/174084.

**Comment by aand18** [comment]
![20200816_014029](https://user-images.githubusercontent.com/36073609/90322811-94d48980-df61-11ea-900d-b3bd733cb362.jpg)
@wb9688 thanks for helping figure this out. I'm trying to understand my confusion an why I had it enabled. 

I understand that you're familiar with YouTube's terminology, but for the random NewPipe user (me) reading "YouTube restricted mode" in NewPipe context, it tells me nothing - restricted in what way? I have no idea what it does. Frankly I don't remember ever hearing about this YouTube feature before, at least not by this name. 

But the toggle comes immediately below "Age restricted content" so they "feel" similar, when actually they're opposites, maybe even mutually exclusive?

May I suggest "filter mature content"? This is how they define it  in the page you linked and it's less ambiguous.

**Comment by opusforlife2** [comment]
How about "Youtube's Restricted Mode" which would imply this is Youtube's terminology and not Newpipe's?

**Comment by snappyapple632** [comment]
Perhaps we cound change the "No comments" error to suggest turning YouTube's restricted mode off?

**Comment by wb9688** [comment]
@snappyapple632: The comments issue is unrelated to Restricted Mode. YouTube changed their mobile site (and then seemed to have changed it back) so comments might not work anymore.

**Comment by opusforlife2** [comment]
@GitterDoneBoi @vdbhb59 Can you see if the two toggles discussed above were causing your issue?

**Comment by jfmcbrayer** [comment]
I get an error popup along with no comments on most videos, but not all. I have restricted mode off, and access to age-restricted content on. This is the debug output.

## Exception
* __User Action:__ requested comments
* __Request:__ https://m.youtube.com/watch?v=nq4h2pkYjIQ
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.20.5
* __OS:__ Linux motorola/river/river:10/QPU30.52-23/e548a:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:97)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:52)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:156)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:95)
	... 30 more

```
</details>
<hr>

**Comment by shameempk** [comment]
I am facing the same issue. Comment works on some videos and it doesn't on some. 
Here is a crash report:
## Exception
* __User Action:__ requested comments
* __Request:__ https://m.youtube.com/watch?v=3hyXuK0VE5g
* __Content Country:__ GB
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.20.5
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:97)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:52)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:156)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:95)
	... 30 more

```
</details>
<hr>

**Comment by mhmdanas** [comment]
@jfmcbrayer @shameempk see https://github.com/TeamNewPipe/NewPipeExtractor/issues/455. Closing this issue.
