### ISSUE TITLE
Could not decrypt video url signature.

### ISSUE THREAD

**Issue by tgp1994** [TeamNewPipe/NewPipe#430]
It looks like this error is back in force with the 0.8.8 update that was posted on F-Droid just a little bit ago.

Trying to open many YouTube links, such as https://www.youtube.com/watch?v=MyrE1hC0HiQ, results in the error "Could not decrypt video url signature." and the video never playing.

**Comment by jerbear64** [comment]
I don't think this is a 0.8.8 issue, as it worked fine yesterday. Rather, I think that Google changed something that broke newpipe.

**Comment by nate2014jatc** [comment]
Error is also present on PureNexus based on 7.1.1 N6F26Q

**Comment by Seferi** [comment]
Same here...

**Comment by Seferi** [comment]
Getting the same error since this morning.. Yesterday it worked fine..

**Comment by nate2014jatc** [comment]
How do we get a stack trace,  so that we can be useful instead of just complaining?

**Comment by theScrabi** [comment]
Ho boy NewPipe is broken ... Thought I could do something else today ...

**Comment by MhhhxX** [comment]
`I/ActivityManager( 2826): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.schabi.newpipe/.MainActivity bnds=[540,1466][750,1704] (has extras)} from uid 10030 on display 0
I/ActivityManager( 2826): Start proc 12715:org.schabi.newpipe/u0a76 for activity org.schabi.newpipe/.MainActivity
I/ActivityManager( 2826): START u0 {cmp=org.schabi.newpipe/.detail.VideoItemDetailActivity (has extras)} from uid 10076 on display 0
I/ActivityManager( 2826): START u0 {cmp=org.schabi.newpipe/.detail.VideoItemDetailActivity (has extras)} from uid 10076 on display 0
I/ActivityManager( 2826): START u0 {cmp=org.schabi.newpipe/.detail.VideoItemDetailActivity (has extras)} from uid 10076 on display 0
I/ActivityManager( 2826): Killing 12715:org.schabi.newpipe/u0a76 (adj 900): remove task
I/WindowManager( 2826): WIN DEATH: Window{c632caf u0 org.schabi.newpipe/org.schabi.newpipe.detail.VideoItemDetailActivity}
I/ActivityManager( 2826): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.schabi.newpipe/.MainActivity bnds=[540,1466][750,1704] (has extras)} from uid 10030 on display 0
I/ActivityManager( 2826): Start proc 12910:org.schabi.newpipe/u0a76 for activity org.schabi.newpipe/.MainActivity
I/ActivityManager( 2826): START u0 {cmp=org.schabi.newpipe/.detail.VideoItemDetailActivity (has extras)} from uid 10076 on display 0
I/ActivityManager( 2826): Displayed org.schabi.newpipe/.detail.VideoItemDetailActivity: +118ms
W/System.err(12910): org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor$DecryptException: Could not load decrypt function
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:815)
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.<init>(YoutubeStreamExtractor.java:217)
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:51)
W/System.err(12910): at org.schabi.newpipe.detail.StreamInfoWorker$StreamExtractorRunnable.run(StreamInfoWorker.java:80)
W/System.err(12910): at org.schabi.newpipe.Downloader.download(Downloader.java:141)
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:794)
I/ActivityManager( 2826): START u0 {cmp=org.schabi.newpipe/.detail.VideoItemDetailActivity (has extras)} from uid 10076 on display 0
I/ActivityManager( 2826): Displayed org.schabi.newpipe/.detail.VideoItemDetailActivity: +108ms
W/System.err(12910): org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor$DecryptException: Could not load decrypt function
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:815)
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.<init>(YoutubeStreamExtractor.java:217)
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:51)
W/System.err(12910): at org.schabi.newpipe.detail.StreamInfoWorker$StreamExtractorRunnable.run(StreamInfoWorker.java:80)
W/System.err(12910): at org.schabi.newpipe.Downloader.download(Downloader.java:141)
W/System.err(12910): at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:794)`

Maybe this is helpful.

**Comment by yasinalm** [comment]
It seems the app is broken. same error for everyone.

**Comment by theScrabi** [comment]
I'm on it.

**Comment by priyankvirani** [comment]
can give me solution for Could not load decrypt function

**Comment by theScrabi** [comment]
Well it's more than that, look at this [here](
https://github.com/rg3/youtube-dl/pull/11892/files#diff-bd8242a0122c5207531954b67e6e51f0R1031).

**Comment by priyankvirani** [comment]
hello sir what i do ?

**Comment by theScrabi** [comment]
[Here are my changes so far](https://github.com/TeamNewPipe/NewPipe/commit/51adb5000b3b3eff2e24254d41bd30900b3c530d).

**Comment by pascalhuber** [comment]
FYI - maybe it helps

> youtube-dl is broken to: #430

youtube-dl works fine for me (NewPipe doesn't), for both versions shown below.

```
~ youtube-dl --version
2017.01.29
```

```
~ youtube-dlold --version        
2017.01.10
~ youtube-dlold https://www.youtube.com/watch\?v\=qYodWEKCuGg
                                                                   
[youtube] qYodWEKCuGg: Downloading webpage
[youtube] qYodWEKCuGg: Downloading video info webpage
[youtube] qYodWEKCuGg: Extracting video information
[youtube] qYodWEKCuGg: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Code Monkey-qYodWEKCuGg.f135.mp4
[download] 100% of 10.66MiB in 00:01
[download] Destination: Code Monkey-qYodWEKCuGg.f251.webm
[download] 100% of 2.82MiB in 00:00
[ffmpeg] Merging formats into "Code Monkey-qYodWEKCuGg.mkv"
Deleting original file Code Monkey-qYodWEKCuGg.f135.mp4 (pass -k to keep)
Deleting original file Code Monkey-qYodWEKCuGg.f251.webm (pass -k to keep)
```

**Comment by theScrabi** [comment]
Yes for Youtube-dl it depends on the Video you are trying to download. youtube-dl needs that signature part only for certain videos but not for all, such like NewPipe does.

**Comment by theScrabi** [comment]
I may need help.

**Comment by cmv47** [comment]
same error

**Comment by theScrabi** [comment]
@cmv47 I don't expect it to work for anyone right now.

**Comment by yasinalm** [comment]
I think [https://github.com/rg3/youtube-dl/commit/3c90cc8b6fc069930264b41f5505dc34c1077442](this) solves the problem.

**Comment by theScrabi** [comment]
Right saw it.

**Comment by BodybuilderSaurabh** [comment]
is the issue resolved now??

**Comment by theScrabi** [comment]
almost, I'm strugling with regex... java (or at least the version I use) does not support named groups.

**Comment by BodybuilderSaurabh** [comment]
The problem is in this line.

helperObjectName = Parser.matchGroup1(";([A-Za-z0-9_\\$]{2})\\...\\(", decryptionFunc);

The value of decryptionFunc

var or=function(){b(!1)};

this is what i think

**Comment by theScrabi** [comment]
Fixed it.

**Comment by Ostefanini** [comment]
If it's fixed, where I can download a version of newpipe fixed ?
Your app is the best for me !

**Comment by theScrabi** [comment]
You may wait until it appears on f-droid.

**Comment by TGSoftware** [comment]
F-Droid uses GitLab for app submissions, and [it is currently down](https://gitlab.com/fdroid/rfp/issues). I have made an unofficial build of 0.8.9 (rename .zip to .apk since GitHub doesn't allow APKs to be uploaded - [NewPipe-0.8.9-debug-UNOFFICIAL.zip](https://github.com/TeamNewPipe/NewPipe/files/745635/NewPipe-0.8.9-debug-UNOFFICIAL.zip) from the releases section for users who don't want to wait. Note that this is an UNOFFICIAL build in debug mode, and it is unsigned. The official (signed) version is the one that will appear on F-Droid. If you do not trust this build, I encourage you to wait until it is officially released on F-Droid.

**Comment by tgp1994** [comment]
@TGSoftware That's interesting, until now the process of going from GitHub to F-Droid was a black box to me. So will NewPipe show up on that issues list once @theScrabi submits it?

**Comment by TGSoftware** [comment]
@tgp1994 I read the rest of that paragraph, and I realized there's more to this process. This process used to happen on the F-Droid forum, but now it is done through Gitlab or IRC. When an app's first version is being submitted, the issue is submitted to the list on Gitlab or as a message on [their Freenode IRC channel](https://botbot.me/freenode/fdroid) (this is used more often), and F-Droid repository maintainers check to see if the requirements are met for publishing (e.g. non-free libraries or proprietary blobs such as Google AdMob or Google Analytics are not included in the source code). Then, the project maintainer either [gets access to a folder on the F-Droid repository and is able to push the update using F-Droid tools (faster)](https://f-droid.org/manual/fdroid.html#Metadata) or asks an [F-Droid developer to publish their app given some details (slower)[https://f-droid.org/contribute/]. If there are updates to the app, the issue can be updated, or the project maintainer is able to publish the update themselves because they have write access to their project on the [Data git repository](https://gitlab.com/fdroid/fdroiddata).

**Comment by theScrabi** [comment]
I submited it, but it takes to long for fdroid to buld. I wrote them a mail about that, but no responce so far.

**Comment by JonasPHess** [comment]
Thanks for fixing this.  You guys saved my day.

**Comment by tgp1994** [comment]
For anyone looking for a status update, it sounds like there's some difficulty getting the app to build for F-Droid (#443).

**Comment by Rat-S** [comment]
Same issue again. Since yesterday.

**Comment by switchtegrax1** [comment]
https://github.com/TeamNewPipe/NewPipe/releases update to 0.14.1 the update is not on fdroid yet

**Comment by jerbear64** [comment]
This was already fixed in the newest release.

**Comment by AndroidDeveloperLB** [comment]
@SirPscl Maybe it wasn't approved yet?
I can still see v 0.14.0 there...

![screencapture-f-droid-org-packages-org-schabi-newpipe-2018-09-13-10_27_45](https://user-images.githubusercontent.com/5357526/45473423-b0b0ce80-b73f-11e8-9bd8-a478854e2899.png)

**Comment by dorakas** [comment]
Same issue for me since today




{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=PtMowGNfhTg",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.14.2",
   "os": "Linux Android 9 - 28",
   "time": "2019-01-18 23:48",
   "exceptions": [
      "org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function \n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:729)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:604)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:51)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:56)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:109)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \"(encodeURIComponent=function\\([a-zA-Z0-9_]+\\)\\{.+?\\})\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:713)\n\t... 30 more\n"
   ],
   "user_comment": ""
}

**Comment by tgp1994** [comment]
@dorakas We're following the current issue  #[here](https://github.com/TeamNewPipe/NewPipeExtractor/issues/133).
