### ISSUE TITLE
Still unable to view age restricted content 

### ISSUE THREAD

**Issue by Educatejag** [TeamNewPipe/NewPipe#4869]
I tried the patch also apk-debug.zip and also release candidate 0.20.3. Still I am not able to view adult sexy contents. 

Previous link where I posted is closed.
https://github.com/TeamNewPipe/NewPipe/issues/4681

Earlier there were no issues and I was able to view all adult content, twerking, stripping etc. Now nothing is showing. 

Please do something.. 

Thank you

**Comment by opusforlife2** [comment]
Loading just fine for me on the RC. Can you ensure your 18+ setting is on and Restricted Mode setting is off?

**Comment by Stypox** [comment]
@Educatejag could you provide a url to such a video? Youtube age restricted tests succeed and we can't reproduce

**Comment by TheProgrammingDog** [comment]
@Stypox this video https://www.youtube.com/watch?v=lBs4T8cEGPM and lots of recent videos from their channel show as content unavailable. On the YouTube app these videos are the ones that require a sign in.

**Comment by Stypox** [comment]
@TheProgrammingDog I have both `settings →content →content language` and `settings →content →content country` set to UK and `settings →content →show age restricted content ` active, and everything loads fine on RC5 of release 0.20.3

Could you install 0_20_3_RC5 connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then we might be able to fix this issue.

**Comment by TheProgrammingDog** [comment]
@Stypox just realised I was using 20.2! sorry for wasting your time :(

**Comment by Stypox** [comment]
Oh ok, no problem ;-) 
This is fixed, then :-D

**Comment by Toshiba1127** [comment]
Where to get 0.20.3?
I have downloaded the latest commit and compile, still not resolved. Here is my har file

[test.zip](https://github.com/TeamNewPipe/NewPipe/files/5559372/test.zip)
