### ISSUE TITLE
Install from NewPipe's custom f-droid repo

### ISSUE THREAD

**Issue by Zykino** [TeamNewPipe/NewPipe#5062]
### Checklist

- [x] I **want to** use the latest version - 0.20.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Install NewPipe (long time ago)
2. Install NewPipe's custom f-droid repo following https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/
3. Export the data
4. Uninstall F-Droid’s version
5. Try to install last version from f-droid app.

### Actual behaviour

 I get an error toast that the asked file was not found this link : https://archive.newpipe.net/fdroid/repo/NewPipe_v0.20.4.apk
But if I check in by browser the file is present and it is indeed the last version.

I can just click the "Install" button and the toast appear again.

### Expected behavior

The last version start to be download and installed.

### Device info

 - Android version/Custom ROM version: OxygenOS 9.0.6 (Android 9 by the manufacturer)
 - Device model: OnePlus 3

**Comment by mhmdanas** [comment]
> I want to use the latest version - 0.20.4

Just wanna say that 0.20.5 has been released. Could you check if this happens when you try to install 0.20.5 too?

**Comment by Zykino** [comment]
Yes I have the same comportment for 0.20.{3,4,5}.

The "NewPipe upstream repository" is activated, and in it both the official and "user" mirror are ON. (https://archive.newpipe.net/{fdroid,archive}/repo). The key look the same but the QRCode is different. I see that there is one appli in the repo.

A bit of strage behavior to me is that the archive is in the same repo than the standard. While for F-Droid and Guardian Project, the Official and Archive repo are different.

I may give too much info, but since I have no clue how this works I wanted to give as much info as I can.

**Comment by TheAssassin** [comment]
Seems like it's not limited to our repository; I've been reported the same issue for some apps on the official repository as well. There's a chance it's just a bug in F-Droid. Perhaps downgrade the F-Droid app and try again?

**Comment by Zykino** [comment]
Well doing as you proposed I found where the bug come from: it is because I have registered both the NewPipe repo and its archive. As I said they are both shown in the same category so that may be the issue.

I installed both of this repo:
> https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501
> https://archive.newpipe.net/archive/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501

When downgrading, I installed both repo on F-Droid 1.9. But for 1.8 I did my lazy self and only installed the first and it found the APK. To be sure of me I removed cache and storage of F-Droid, added the "archive" repo and I got back to the same problem of a toast telling me the apk is not found. Tried back on F-Droid 1.10 and worked the same (also work by inactivating the archive as mirror.)

So I am not sure how is it configured on your side but I think that The archive Repo should have a different name.
By default there is:
```
F-Droid Archive [ ]
F-Droid [x]
Guardian Project Archive [ ]
Guardian Project [ ]
NewPipe upstream repository [x]
(And I think there should have "NewPipe upstream repository Archive [ ]")
```

Tell me if I am not clear it is already way too late at the time of writing this :s

**Comment by TheAssassin** [comment]
Well, in the config, the archive is called "NewPipe upstream archive", whereas the main repo is called "NewPipe upstream repository". I think that's quite distinct already.

**Comment by Zykino** [comment]
Following the XML files I am either really bad with English, or this sentence in the blog post is plain wrong. It should say to replace `repo` (not `fdroid`) with `archive`.
> Note: we also provide an archive containing older builds of NewPipe; to use this, just substitute fdroid with archive in the URL, the key’s fingerprint is the same.)

Anyway I just tested to add the archive repos with the good URL and it still registered in "NewPipe upstream repository" instead of creating another repo section. And I also get the toast telling me the apk is not present.
But since I am back with the latest F-Droid version maybe this is a bug on their side and/or a bad understanding/documentation on what makes a repo a mirror of another one and what makes it a distinct repo.

Like you I feel like the name difference should be enough, but maybe they consider a repo a mirror of an other one if they share the same `pubkey`. I did not read the F-Droid doc about creating/managing own repo.
And they also may have a bug that I should report when a file exist in one mirror but not another one the file is listed but is not downloadable. (And this trigger the toast.)

**Comment by TheAssassin** [comment]
> Following the XML files I am either really bad with English, or this sentence in the blog post is plain wrong. It should say to replace repo (not fdroid) with archive.

Fixed.

**Comment by ShareASmile** [comment]
This can be closed as solved @mhmdanas

**Comment by Zykino** [comment]
Well to be perfectly honest, on my phone if I try to retrograde to 0.20.4 while having both repo (the good ones) activated, F-Droid still show me the same toast (in french):
> Le fichier demandé n’a pas été trouvé.
> https://archive.newpipe.net/fdroid/repo/NewPipe_v0.20.4.apk

I did not yet checked if an issue like this one is reported to F-Droid. I still need to either add a link back to this issue and help them fix on their side or create an issue there.
