### ISSUE TITLE
Phone restarts when opening a video

### ISSUE THREAD

**Issue by Goth11** [TeamNewPipe/NewPipe#5961]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Press on a video to open it

### Actual behaviour

Phone suddenly restarts itself, but it doesn't happen always, seems to be at random times. After it restarts, the phone appears to be lagging a bit until I close the app. Last time it happened the restart screen froze. This bug only started happening after the last update.

### Device info

 - Android version/Custom ROM version: Android 11 (MIUI 12.1.4)
 - Device model: Xiaomi Mi 10 Lite 5G

**Comment by TiA4f8R** [comment]
What do you want to say by restart?
Do you got the lockscreen after a black screen for a few seconds or your device start animation, with MIUI logo?

**Comment by Goth11** [comment]
https://user-images.githubusercontent.com/42772160/113160654-58cb0c00-9246-11eb-962e-3c8d81f45d5e.mp4

**Comment by TiA4f8R** [comment]
Thank you for screencast.
So it is a framework crash. Can you try this APK please: https://github.com/TeamNewPipe/NewPipe/suites/2386871925/artifacts/50699858 and see if it works without any crash? Thanks!

**Comment by Goth11** [comment]
I tried it a while and it worked, didn't crash

**Comment by Goth11** [comment]
Update: after I imported the database from the normal version, it crashed again, so maybe it has something to do with that?

**Comment by Goth11** [comment]
I actually just tried this, and found out that the problem is watch history. When it is disabled, the crash happens, and when it is enabled, it doesn't (same on both the original apk and the one you sent me).

**Comment by TiA4f8R** [comment]
@Goth11 Thanks for your researches.
Can you try this APK https://github.com/TeamNewPipe/NewPipe/suites/2390804303/artifacts/50805040 and repeat my steps above? A crash in the watch history just got fixed with #5971, maybe it's related. Thanks again!

**Comment by Goth11** [comment]
It crashes as well. 
Like I said, it didn't have this problem until the last update, so maybe there is some change in the last update regarding watch history that is the problem?

**Comment by TiA4f8R** [comment]
Oh, no. We need again your help.
Can you try to capture logs with ADB and search for exceptions (I'm know it's hard in a very big text file)? Thanks!
Note that you can't maybe get the stack trace because it's a framework crash and not an app crash.

**Comment by TiA4f8R** [comment]
Yes, there were some changes. We are investigating.

**Comment by TiA4f8R** [comment]
@Goth11 Can you help us again by trying to get logs from your system with ADB?
Then try to search for exceptions in the logs you got and post on this issue these exceptions. However, you may be not able to find any exception related to this issue because it's a crash from the Android Framework, not an app.
Thank you again for your researches.

**Comment by Goth11** [comment]
Crash logs:
https://pastebin.com/nHHkVQLj

**Comment by TobiGr** [comment]
@Goth11 Thank you for getting the log. Which NewPipe version did you use before?
I could not find anything related to history in the logs, but some note about creating the audio session and gaining audio focus. I do not understand all parts of the log. Maybe @Redirion can help us to understand what was going wrong.

**Comment by Redirion** [comment]
@Goth11 can you send the full logcat with the crash? I think it would help to to also have main log so we can see what newpipe did before the crash occurred.

**Comment by Redirion** [comment]
okay, I think I found the issue. It crashes here:
https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/video/VideoFrameReleaseHelper.java#L389

ExoPlayer 2.12. Changelog:
"*   Pass frame rate hint to `Surface.setFrameRate` on Android 11."

**Comment by Redirion** [comment]
@avently can you take a look at the video? It might be some kind of racing issue. The video buffering is not done, then it gets moved down for playback in background and the next video is clicked. setFrameRate seems to be called while the first video view gets destroyed/recycled to play the next video.

Chances are that this can be fixed within NewPipe if we can add a small delay somewhere but otherwise this seems to be either an ExoPlayer or device issue.

**Comment by Goth11** [comment]
> 
> 
> @Goth11 Thank you for getting the log. Which NewPipe version did you use before?
> I could not find anything related to history in the logs, but some note about creating the audio session and gaining audio focus. I do not understand all parts of the log. Maybe @Redirion can help us to understand what was going wrong.

The last version I used was 20.9 but I'm using NewPipe for some months now and always updated it so I used older versions as well and none had this bug.

**Comment by Goth11** [comment]
> 
> 
> @avently can you take a look at the video? It might be some kind of racing issue. The video buffering is not done, then it gets moved down for playback in background and the next video is clicked. setFrameRate seems to be called while the first video view gets destroyed/recycled to play the next video.
> 
> Chances are that this can be fixed within NewPipe if we can add a small delay somewhere but otherwise this seems to be either an ExoPlayer or device issue.

But why does the crash only happen when watch history is disabled, and when it is enabled it doesn't? I don't see the connection.

**Comment by Goth11** [comment]
Ok so I just found out that the crash happens if watch history is disabled AND I go from a video to another one. That is, if I play a video, close it, and play another, it's fine, but if I keep it in background and play another one or I choose one from the watch next tab, it crashes (only with watch history disabled!)

**Comment by avently** [comment]
@Redirion no time, sorry. Rewriting a big part of my app. If it's related to ExoPlayer's update just create an issue and link the guys who made this change. Maybe they'll give some important insights

**Comment by avently** [comment]
@Goth11 in all such cases a screen record will be the most useful thing. Can you make it and upload? Without the very last step that crashes the phone

**Comment by Goth11** [comment]
The crash would happen if right at the end, with the video in the background, I'd play another one
https://drive.google.com/file/d/17wLx_-goo2ht0Z4ndoW6dgBUF2jE7i-g/view?usp=sharing

**Comment by avently** [comment]
@Goth11 the link is not publicly available

**Comment by Goth11** [comment]
Sorry, it should be now.

**Comment by avently** [comment]
Oh, man. You have already uploaded a video with the issue. My github client doesn't show such videos at all so I missed it. Ok. Based on the first video I can't say that it can be NewPipe bug.

**Comment by Goth11** [comment]
Yes but on the second video you can see that the crash is connected to a certain NewPipe setting.

**Comment by bloatware99** [comment]
https://github.com/TeamNewPipe/NewPipe/suites/2386871925/artifacts/50699858
 &&&&
https://github.com/TeamNewPipe/NewPipe/suites/2390804303/artifacts/50805040
 I tried both fixed app trial still get my device is flashing when opening some videos,  During flashing time I force to restart the device otherwise my shows the crictical move i.e, Factory reset mobile and ask to clear all the  internal memory.

**Comment by Redirion** [comment]
Please try this apk: https://github.com/TeamNewPipe/NewPipe/suites/2492189832/artifacts/53772067

**Comment by Goth11** [comment]
I'm not having this issue anymore on any version of the app and the only thing that changed is that I updated to MIUI 12.1.5, maybe that solved the problem somehow.

**Comment by avently** [comment]
Lol, MIUI as always:)

**Comment by Redirion** [comment]
closing this then

**Comment by bloatware99** [comment]
Still I'm having that issue

**Comment by Redirion** [comment]
did you try the apk I have linked?

**Comment by bloatware99** [comment]
> Please try this apk: https://github.com/TeamNewPipe/NewPipe/suites/2492189832/artifacts/53772067

I have tried this app still facing that issue. My device motorala, one power model. Stock android 10 OS running

**Comment by Redirion** [comment]
okay my apk was a fix for Android 11. Do you have watch history disabled?

**Comment by bloatware99** [comment]
Yes , I have
![Screenshot_20210416-201009](https://user-images.githubusercontent.com/65462601/115041167-d736d780-9eef-11eb-9884-23e650b89f99.png)

**Comment by Redirion** [comment]
and does it work if you enable history test-wise?

**Comment by bloatware99** [comment]
I updated  today  NewPipe version v0.21.2 still some random video restarting my device , FYI I tried last four updates still same issue going , Badly when I didn't force restart the device , it automatically goes through tge factory reset option. I hope dev will fix this issue soon.

**Comment by jithinjames916** [comment]
I too try NewPipe version v0.21.2 still clicking a new vedio while playing other restarts my device...
One of the version 'newpipe surfaceframeratewrkrnd version v0.21.1.' still works perfectly.. hope u do something to fix this issue soon...

**Comment by bloatware99** [comment]
Whwre can I download the surfaceframeratewrkrnd version v0.21.1 , let I have to try.

**Comment by TiA4f8R** [comment]
@bloatware99 @jithinjames916 @musq @Goth11 Can you reproduce this bug with the last release candidate of the 0.21.3 version or not?

**Comment by bloatware99** [comment]
> @bloatware99 @jithinjames916 @musq @Goth11 Can you reproduce this bug with the last release candidate of the 0.21.3 version or not?

@

> @bloatware99 @jithinjames916 @musq @Goth11 Can you reproduce this bug with the last release candidate of the 0.21.3 version or not?

Where can I get version 0.21.3?  I

**Comment by TiA4f8R** [comment]
It's still not released, see #6357, which is pinned.

**Comment by bloatware99** [comment]
> It's still not released, see #6357, which is pinned.
Here I have attached the trail video of NewPipe Release 0.21.3 still the same issue restarts playing video.
https://user-images.githubusercontent.com/65462601/119881494-f8f19880-bf4a-11eb-855d-d339ace26226.mp4

**Comment by TiA4f8R** [comment]
> > It's still not released, see #6357, which is pinned.
> 
> Here I have attached the trail video of NewPipe Release 0.21.3 still the same issue restarts playing video.
> 
> https://user-images.githubusercontent.com/65462601/119881494-f8f19880-bf4a-11eb-855d-d339ace26226.mp4

Just to know, did you disable the `Show thumbnail` option in the notification settings and then tried to reproduce the bug?

**Comment by bloatware99** [comment]
> > > It's still not released, see #6357, which is pinned.
> > 
> > 
> > Here I have attached the trail video of NewPipe Release 0.21.3 still the same issue restarts playing video.
> > 
> >   
> >     
> >     
> > 
> >     TRIM_20210528_001821.mp4
> 
> Just to know, did you disable the `Show thumbnail` option in the notification settings and then tried to reproduce the bug?

@TiA4f8R  After disable of `Show Thumbnail` there is not restarting issue. I trailed more than 3 different videos that caused before. Now playing fine.
![Screenshot-newpipe](https://user-images.githubusercontent.com/65462601/119972880-61cf2400-bfd0-11eb-80bd-d6830b56e486.jpeg)

**Comment by bloatware99** [comment]
@TobiGr @Redirion  sir,  When open the link via whatsapp NewPipe became crashed.

**Comment by TiA4f8R** [comment]
@bloatware99 Please stop posting this type of comments, especially where they are off-topic to an issue. We are not an on-demand service. Update to 0.21.3 to fix this problem.

**Comment by KatoriYuu** [comment]
@TiA4f8R @Redirion I can still reproduce this problem with the lastest version (0.21.5) on Nokia 8.1. Disabling watch history seems to cause the bug.

**Comment by TobiGr** [comment]
@KatoriYuu Can you try to get a full log via ADB? We already have [this one](https://github.com/TeamNewPipe/NewPipe/issues/5961#issuecomment-811856198), but I'd like to see one from a different device.

**Comment by KatoriYuu** [comment]
@TobiGr Here you are:
--------- beginning of crash
09-27 08:31:33.257   541   541 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 541 (init), pid 541 (init)
09-27 08:31:33.276   541   541 F libc    : crash_dump helper failed to exec
09-27 08:31:33.289   545   545 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 545 (init), pid 545 (init)
09-27 08:31:33.303   545   545 F libc    : crash_dump helper failed to exec
06-19 19:45:25.793  2991  2991 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 2991 (init), pid 2991 (init)
06-19 19:45:25.822  2991  2991 F libc    : crash_dump helper failed to exec
06-19 19:46:32.652   886   886 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc60 in tid 886 (surfaceflinger), pid 886 (surfaceflinger)
06-19 19:46:32.712  7124  7124 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-19 19:46:32.712  7124  7124 F DEBUG   : Build fingerprint: 'Nokia/Phoenix_00WW/PNX_sprout:11/RKQ1.200906.002/00WW_6_210:user/release-keys'
06-19 19:46:32.712  7124  7124 F DEBUG   : Revision: '0'
06-19 19:46:32.712  7124  7124 F DEBUG   : ABI: 'arm64'
06-19 19:46:32.712  7124  7124 F DEBUG   : Timestamp: 2021-06-19 19:46:32+0700
06-19 19:46:32.712  7124  7124 F DEBUG   : pid: 886, tid: 886, name: surfaceflinger  >>> /system/bin/surfaceflinger <<<
06-19 19:46:32.713  7124  7124 F DEBUG   : uid: 1000
06-19 19:46:32.713  7124  7124 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc60
06-19 19:46:32.713  7124  7124 F DEBUG   : Cause: null pointer dereference
06-19 19:46:32.713  7124  7124 F DEBUG   :     x0  0000000000000000  x1  0000000000000000  x2  0000007fdf7ed5d8  x3  0000000000000000
06-19 19:46:32.713  7124  7124 F DEBUG   :     x4  0000000000000010  x5  0000000000000008  x6  0000007498b87000  x7  0000000000004648
06-19 19:46:32.713  7124  7124 F DEBUG   :     x8  0000000000000001  x9  00000000000fffff  x10 0000000000000002  x11 0000000000000000
06-19 19:46:32.713  7124  7124 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 002671eb1fe44600  x15 000062cf68ff5e1c
06-19 19:46:32.713  7124  7124 F DEBUG   :     x16 000000749714e240  x17 00000074971a4bb4  x18 0000007497bc4000  x19 00000073b57e8ba0
06-19 19:46:32.713  7124  7124 F DEBUG   :     x20 00000073b57e8b30  x21 0000007285802270  x22 0000000000000000  x23 0000000000000000
06-19 19:46:32.713  7124  7124 F DEBUG   :     x24 00000074978c5000  x25 00000074978c5000  x26 0000000000000000  x27 0000000000000007
06-19 19:46:32.713  7124  7124 F DEBUG   :     x28 0000000000000001  x29 0000007fdf7ed590
06-19 19:46:32.713  7124  7124 F DEBUG   :     lr  000000749707f538  sp  0000007fdf7ed590  pc  0000007497024bb8  pst 0000000040000000
06-19 19:46:32.744  7124  7124 F DEBUG   : backtrace:
06-19 19:46:32.744  7124  7124 F DEBUG   :       #00 pc 00000000000debb8  /system/lib64/libsurfaceflinger.so (android::Layer::setFrameRate(android::Layer::FrameRate)+32) (BuildId: 075eab333e600e753196092a75d5c69d)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #01 pc 0000000000139534  /system/lib64/libsurfaceflinger.so (_ZNSt3__120__packaged_task_funcIZN7android14SurfaceFlinger12setFrameRateERKNS1_2spINS1_22IGraphicBufferProducerEEEfaE4$_68NS_9allocatorIS8_EEFNS1_4$_69EvEEclEv$eacff03f351b4b46958ae206dfdcefa1+116) (BuildId: 075eab333e600e753196092a75d5c69d)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #02 pc 00000000001392bc  /system/lib64/libsurfaceflinger.so (_ZN7android4TaskIZNS_14SurfaceFlinger12setFrameRateERKNS_2spINS_22IGraphicBufferProducerEEEfaE4$_68E13handleMessageERKNS_7MessageE$eacff03f351b4b46958ae206dfdcefa1+80) (BuildId: 075eab333e600e753196092a75d5c69d)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #03 pc 000000000001a2b0  /system/lib64/libutils.so (android::Looper::pollInner(int)+368) (BuildId: 7a6d320f655acb7aedf68c347bbd8caf)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #04 pc 000000000001a0d8  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: 7a6d320f655acb7aedf68c347bbd8caf)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #05 pc 00000000000faa94  /system/lib64/libsurfaceflinger.so (android::impl::MessageQueue::waitMessage()+84) (BuildId: 075eab333e600e753196092a75d5c69d)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #06 pc 000000000010c284  /system/lib64/libsurfaceflinger.so (android::SurfaceFlinger::run()+12) (BuildId: 075eab333e600e753196092a75d5c69d)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #07 pc 00000000000023a0  /system/bin/surfaceflinger (main+856) (BuildId: 26e759f8251949ab43cf08bd8b50d077)
06-19 19:46:32.744  7124  7124 F DEBUG   :       #08 pc 0000000000049098  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: a6129197241eb9f68acb05fe7e48a951)

**Comment by KatoriYuu** [comment]
@litetex It seems to get worse with the current version (0.21.12). Enabling watch history used to temporarily fix the problem, but the trick is useless right now :( . I haven't found any other workaround at the moment, so if you need any more information, please let me know. I'm very willing to help as much as I can :)

**Comment by litetex** [comment]
I don't think we can do anything on app side as this is a Android OS bug.

I searched the Google issuetracker for more information and found this:
https://issuetracker.google.com/issues/177022431

Issue description (opened at 2021-01-11):
> On Android R, it was observed some occasional crashes, not 100% reproducible.
> By the logs, we nailed down the crash to a NULL pointer dereference on Layer.cpp:
> 
> 
> A SIGSEV fault was observed.
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc60
> Cause: null pointer dereference
> 
> It seems the crash is happening in following statement, some issue with == operator overloading but it is not clear how this is causing null pointer access issue.
> 
> 
> bool Layer::setFrameRate(FrameRate frameRate) {
> 
> if (mCurrentState.frameRate == frameRate) {
> return false;
> } 

However the issue was closed with "This was opened on the wrong component." and I'm unable to find any similar issue.

**Comment by kuroodo** [comment]
I have experienced this same issue as described in my duplicate issue mentioned above.

I managed to reproduce the crash with Android Studio's android emulator. The emulator is a Pixel 2, API level 30, x86_64, and with play store enabled. I have also reproduced the crash in another emulated device which is a Nexus One, API Level 30, x86_64, and no play store.

To reproduce the crash:
- Have a fresh installation of NewPipe 0.22.1
- Go to History and Cache settings
- Disable Resume Playback
- Search for or select a video
- Allow the video to load and begin playing
- Select a different video

The above steps should produce the crash. Note that this crash does not happen if you play the first video in the background or as a popup. The issue seems to involve the resume playback setting. When this setting is enabled, even on my physical device, the crash no longer occurs. Disabling it causes the crash to occur.

Since the video file is too big, [I have uploaded a youtube video showing the crash with LogCat logs.](https://www.youtube.com/watch?v=L9voVoMc3A4)
Here's the log shown in the video
[log.txt](https://github.com/TeamNewPipe/NewPipe/files/8193078/log.txt) or https://pastebin.com/gkqYwycA

**Comment by TiA4f8R** [comment]
Sorry, I forgot to change the link. It's fixed in my comment above (I removed the previous number from comments, to be sure to not link the future issue/PR to this issue).

**Comment by kuroodo** [comment]
I tried the APK of the PR and can still reproduce the issue using the steps I provided in my previous comment, using the same emulators.

**Comment by TiA4f8R** [comment]
Ok, so the issue seems to be not fixable by us I am afraid, because it's an issue from your Android system on which we cannot do something ourselves (see above).

**Comment by Redirion** [comment]
in case the crash is resulting from setFrameRate the newer ExoPlayer version offers the ability to turn that off:
[82138](https://github.com/google/ExoPlayer/commit/0097a79c2d221dc55ef1147f6f3144f2735a997a)

**Comment by ShareASmile** [comment]
Is this still a issue ? on latest  version
[v0.25.1](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.25.1)

**Comment by kuroodo** [comment]
Issue appears to be fixed for me on v0.25.1
