### ISSUE TITLE
Specific videos keep buffering/loading every few seconds while having enough network bandwith

### ISSUE THREAD

**Issue by 0x4c47** [TeamNewPipe/NewPipe#6376]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Have internet connection capable of instantly loading 1080p and even 1080p60 and 4k60 videos. Mine has a Download bandwith of 250Mbit/s that can be measured with online speedtests.
2. Open specific videos, e.g. https://www.youtube.com/watch?v=gmyFNHe9EIY
3. Set quality to 1080p for maximum lagging/loading or 360p for still noticeable issues with loading.
4. Open video on YouTube and everything's fine and loading very fast.

### Actual behaviour

Video keeps buffering/playing/buffering and the loading icon appears every few seconds for 1 second.

I'm noticing this for months and several Android and NewPipe versions now. Most videos are fine but approx. one out of ten videos that I watch are unwatchable on NewPipe because of this and I switch to the browser where everything's fine.

I also tested it on other internet connections and experience the same issue there. Other videos on NewPipe are completely fine, even on 1080p60.

### Expected behavior

Video loads and plays  fast and smoothly as on youtube.com.

### Screenshots/Screen recordings

https://streamable.com/tw5gk3

In the last part where evrrythimg's black I wanted to show that the playback with YouTube in the browser is completely fine. No lags and very fast buffering at 1080p as expected for my connection. But my browser prevented the system from recording it... I can say for sure that it always works fine there. I'm skipping through the
video in the screen recording because this only happens for non-cached video parts.

### Device info

 - Android version/Custom ROM version: LineageOS 18.1 (Android 11) and LineageOS 17.1 (Android 10)
 - Device model: Pocophone F1

**Comment by racrbmr** [comment]
mine is Poco F1 too, and it had exact problem.

**Comment by 0x4c47** [comment]
Just discovered another video where this issue is present for me: https://www.youtube.com/watch?v=rP1IMdE3C74

But this time it was a bit different. I force quit the app and reopened it. After that the video was playing fine without any issues on the very same quality settings.
I tried that for the video mentioned in the issue description but it didn't fix it.

**Comment by opusforlife2** [comment]
Fixed by #6444. Please wait for the next release.

**Comment by kenktk** [comment]
Even after patch 0.21.5, this problem still occurs for me. When I use the browser with the same video settings, it plays perfectly. As the original issue said, it happens every so often. Some videos are worse than others and some don't have it at all. 
Pixel 3a
GrapheneOS
Average internet download around 200 Mbps.

**Comment by 0x4c47** [comment]
I don't know if it's the same issue but this actually got a lot worse for me in the meantime. I think it was already getting worse after the release that included #6444.

I experience this issue more often now. Approx. every 3rd video takes a very long time to initially load and buffers often. Sometimes closing the app and reopening helps. Sometimes not. I don't recognize any other pattern.

And again: When I open the video in YouTube in the browser, playback is completely fine on the highest quality settings. No buffering at all and the buffering progress bar jumps far beyond the current position instantly.

In Newpipe I can see the buffering progress bar going very slowly for the hanging videos. And also overall the buffering doesn't go far beyond the current position (compared to YT in the browser).

**Comment by 0x4c47** [comment]
Quick fix that works for me: Tap the current progress bar position a couple of times when the issue occurrs. After that the buffer indicator of the progress bar jumps forward quite fast and the issue is gone for the video currently playing...

**Comment by opusforlife2** [comment]
@0x4c47 Please see the pinned issue for further updates. You can test the PR linked there. The fix mentioned here turned out to be inadequate.

**Comment by 0x4c47** [comment]
Seems like the most recent version 0.21.8 finally fixed this for me. Just tried several videos and I didn't experience the buffering issue any more.

Buffering is still not as fast as on the YouTube site in the web browser but the release notes hint at some throttling done by YouTube so maybe that's still an issue.
