### ISSUE TITLE
Unable to access non-kid friendly videos

### ISSUE THREAD

**Issue by JulienGn** [TeamNewPipe/NewPipe#6572]
### Checklist

- [x] I am using the latest version - 0.21.5
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Search for an age restricted video. I allowed them in my settings

Example of video too borderline for poor YouTube : Misleading Title by DJ S3RL

### Actual behaviour

The video data won't load, the previous video will keep running.
`

### Expected behavior

Loading my non kid music videos without having to provide my actual ID to YouTube .

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=g9Ttm46ASk8
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.21.5
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:6)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchVideoInfoPage(YoutubeStreamExtractor.java:802)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:731)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>`

### Device info

 - Android version/Custom ROM version: Linux Android 9 - 28
 - Device model: Xiaomi 9 Pro

**Comment by SameenAhnaf** [comment]
Expected to be fixed in next update as TeamNewPipe/NewPipeExtractor#665 is merged.

**Comment by TiA4f8R** [comment]
Duplicate of #6403.

**Comment by JulienGn** [comment]
On a side note, this is fixed, for now, with the test release of 0.21.6

Until YouTube strikes again I guess

**Comment by edo0** [comment]
@JulienGn @TiA4f8R 
This is again/still broken in version 0.21.6
![Screenshot_20210718-111307_NewPipe](https://user-images.githubusercontent.com/16632292/126061945-b6c7d4ba-a88c-40e1-a3e7-e56f08587caf.png)
