### ISSUE TITLE
When videos end the seekbar sometimes ends 1 sec ahead or 1 sec behind the video's supposed total time length

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#6867]
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play any video to the end
2. Look at seekbar time displays
3. (Bug only happens on certain videos)

### Actual behavior

Sometimes the seekbar will show 1 sec shorter has played or 1 sec longer has played than the posted total video duration (at the end of a video)

### Expected behavior

It should always display that it ended on the total duration

### Screenshots/Screen recordings

![NewPipe seekbar bug2_2021-07-30_12-50-13](https://user-images.githubusercontent.com/29090831/128605231-99f13924-de8f-4992-8db4-e1e3b7b17024.jpg)

### Logs
n/a

### Device info

 - Android version/Custom ROM version: 8.0
 - Device model: Samsung Galaxy S7 Edge

**Comment by infinitewaveparticle** [comment]
As the screenshot shows it played fhe whole video, but shows that it ended at 2:37 instead of 2:38. Sometimes videos will end at, for example, 11:48 when the total time shown is 11:47. The screenshots I have are from 0.21.7, but the issue is identical in 0.21.8.

**Comment by litetex** [comment]
@infinitewaveparticle 
I think this should be fixed with #7176. Could you please recheck?

**Comment by infinitewaveparticle** [comment]
The seekbar now stops where it should after you open the videos and play them til the end, but some times still show differently from the trending or search list and when you open them. For example the Teofimo vs Kambosos Jr fight highlights says the length is 15:05 in Trending, but when you open it the length is 15:04. Not a big deal, but it's good to be accurate.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
It seems that some videos show the correct time length while others show 1 second less. I suspect this could be an issue with rounding and that the querying of or calculations for determining and/or displaying the video length aren't written the same for the different areas of the app.

Sent from ProtonMail mobile

-------- Original Message --------
