### ISSUE TITLE
Video restarts whenever a video reached its end while in background playback mode and app is reopened afterwards

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#6907]
### Checklist

- [x] I am using the latest version - 0.21.8 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start playing a video. 
2. Minimize the app so the video plays in the background (not PIP mode) 
3. Wait for the video to end 
4. Reopen app
5. Video will play from the start, resetting the playback marker in the progress

### Actual behavior

The app restarts the video from the very beginning

### Expected behavior

The video shouldn't restart

### Screenshots/Screen recordings

https://youtu.be/5yf5Wn1ZWOU

### Device info

 - Android version/Custom ROM version: Android 11 / OxygenOS
 - Device model: Oneplus 9 Pro

**Comment by opusforlife2** [comment]
> I am using the latest version - x.xx.x

...

**Comment by AlertSubject** [comment]
> > I am using the latest version - x.xx.x
> 
> ...

Oops sorry. Thought I was just supposed to check it I actually do and then set the cross
I do, according to the releases page

**Comment by opusforlife2** [comment]
The video you've linked isn't available.

**Comment by vitaliyg2** [comment]
I have the same issue. It happens when phone was locked while playing video, video reached the end; unlocking phone causes video to restart from beginning.

**Comment by opusforlife2** [comment]
@vitaliyg2 Thanks for the steps to reproduce.

**Comment by Dangelman** [comment]
Can confirm it's a thing. And of you're playing a playlist, unlocking the phone after it ended will restart it from the first video.

**Comment by vitaliyg2** [comment]
Should be fixed in  #7381

**Comment by opusforlife2** [comment]
Closing until someone comments it wasn't fixed by the PR.

**Comment by Dangelman** [comment]
> Should be fixed in #7381

I've updated to 0.21.14 but I still get the bug. I saw the video you linked, I think the problem is that they're using the portraying mode as example. The video still restarts when you turn on the screen if it's in landscape.
