### ISSUE TITLE
Play button on a connected device doesn't resume playback after exiting NewPipe.

### ISSUE THREAD

**Issue by Rikests** [TeamNewPipe/NewPipe#7086]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Connect an external device with play/pause button, like Bluetooth speaker/headset.
2. Open NewPipe.
3. Start playback of media in background or other mode.
4. Open the Android notification drawer.
5. Press "X" on the NewPipe playback notification in the notification drawer.
6. Press Play/Pause button on the connected external device.
7. NewPipe notification appears with a hourglass icon instead of play button.
8. Sit in silence.

### Actual behavior

This happens when NewPipe is **closed** and has been the last app playing media. Newpipe does not resume playback when play/pause button is pressed on a connected external device. Instead It just opens a Notification with a hourglass icon.
This is annoying when trying to resume playback without interacting with the phone directly. Like when I am driving a car with a bluetooth audio system or using a headset. I have to take the phone out of the pocket, navigate to the media, and press play. This is tedious and can be a bit dangerous when driving a car or a bike.

### Expected behavior

I expect NewPipe to resume playing the last playlist, in background mode, or maybe in the mode that was last active.

OR pass the playback command to the next media app that has been open before NewPipe, like VLC, RadioDroid, etc...

### Screenshots/Screen recordings

Here is a screen recording of the issue, note that I am pressing the play button on an external bluetooth speaker, just watch the newpipe notification icon appear to know when I am pressing it.
Video will be deleted on Nov 09, 2021
https://files.fm/f/kupzscvun

Here is a screenshot of the notification.
![image](https://user-images.githubusercontent.com/7914353/132829620-5b7623d1-af62-4e3f-881c-2d24ea42370a.png)

### Device info

 - Android version/Custom ROM version: Android 10 / LineageOS 17.1
 - Device model: SM-G950F (Samsung galaxy s8)

This was also happening on my OnePlus X

_Thank you for developing and maintaining this wonderful app!
-Rikests_

**Comment by Ammako** [comment]
#5122

**Comment by ackzsel** [comment]
Could this be related to #2373 which should get fixed in 0.21.10?

**Comment by Rikests** [comment]
> 
> 
> Could this be related to #2373 which should get fixed in 0.21.10?

Now, after the 0.21.10 release, we can see that It was not related. I upgraded to version 0.21.10 and this issue is still happening.

![Screenshot_20210921-215457_Trebuchet](https://user-images.githubusercontent.com/7914353/134231779-93b8c9f8-dac5-4522-847f-d2c4c33d1a9f.jpg)

**Comment by TacoTheDank** [comment]
Hello, does this issue still occur on version 0.22.1?

**Comment by ackzsel** [comment]
Just checked. For me it still does on 0.22.1. What I did:
* listen to music (using vanilla) over bluetooth headphones
* open newpipe
* start any yt video
* press X to close video
* press play button on bt headphones
Now the [Unknown] track starts
If I close newpipe and/or lock my phone before pressing play the same thing happens. After I manually restart the music the play button is assigned to vanilla again.

**Comment by Rikests** [comment]
> I don't think anything can be done about this, but I'm not a dev.

It could load up the last video/playlist that was played from history in the background player, so that it doesn't just stand there with empty notification, like the one in pic below. When I press play in the car, I often don't care what starts playing as long as something plays.

![image](https://user-images.githubusercontent.com/7914353/163809073-7eaadd89-5faf-4965-9109-99043e7b9485.png)

**Comment by flt4ever** [comment]
1st, great app much appreciate its development! Now, regarding this resume bug, I can confirm it's still happening with version 0.24.1. For me, the test is by getting back in my car after a stop anywhere. I can also say that resuming is no problem when using DI.fm app...not sure about others.
