### ISSUE TITLE
Keyboard not popping up whe pressing search sometimes

### ISSUE THREAD

**Issue by Omar-tamer** [TeamNewPipe/NewPipe#7089]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Press on the search button

### Actual behavior 
sometimes when i go to search for something on newpipe when pressing the search icon the keyboard doesnt appear as expected im forced to click on the x icon and press search again for it to work

### Expected behavior 
keyboard appears reliably

### Device info

 - Android version/Custom ROM version:
 - Device model: im using stock android 10 on a galaxy a51
 - i have simple keyboard installed which works normally in other apps.

**Comment by opusforlife2** [comment]
No step in the checklist is optional. Please carry out the missing step.

**Comment by Omar-tamer** [comment]
> No step in the checklist is optional. Please carry out the missing step.

Done

**Comment by opusforlife2** [comment]
>  I am using the latest version - x.xx.x 

This important info is still missing. Please be very thorough when filling the template. It makes everyone's life easier.

**Comment by CrimsonFork** [comment]
Not original author but same issue, here's my report:

### Checklist
- [x] I am using the latest version - 0.21.13
- [x] I checked, did find a duplicate, this one right here.
- [x] I have read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] This issue contains only one bug.

### Steps to reproduce the bug
1. Open app after it's been closed
2. Press the search button

### Actual behavior
The first time pressing the button, as well as the emerging text field does not call the software keyboard, closing the search and opening it again works as expected, unless the app has been unfocused, in which case the behavior is not consistent.

### Expected behavior
Keyboard being called every time the search bar is focused.

This bug is not present in Legacy 0.20.8

### Device info

 - Android version/Custom ROM version: Stock Rom 6 & 7, as well as LineageOS 17.1 (Android 11)
 - Device model: YT3-X50F, XT1771 and XT1604 respectively

**Comment by CrimsonFork** [comment]
I have a rooted device and basic ADB knowledge if that helps.

**Comment by opusforlife2** [comment]
@CrimsonFork Please open a new issue with this info.

**Comment by CrimsonFork** [comment]
@opusforlife2 [Done](https://github.com/TeamNewPipe/NewPipe/issues/7490).
