### ISSUE TITLE
Unable to import subscriptions

### ISSUE THREAD

**Issue by highvortex** [TeamNewPipe/NewPipe#7122]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'subscriptions'
2. Press on 'import from previous export'
3. Choose the import file .'
 

### Actual behavior

When the subscription file is selected the app crashes

### Expected behavior

Subscriptions imported successfully

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@dd8b371 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{987649a 10501:org.schabi.newpipe/u0a206} (pid=10501, uid=10206) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{987649a 10501:org.schabi.newpipe/u0a206} (pid=10501, uid=10206) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6820)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2935)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:115)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
	... 8 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Calyx OS 2.9 (Android 11)

**Comment by highvortex** [comment]
Trying to import from Invidious export XML file. Also tried Google takeout but saw it was fixed in the next version

**Comment by Gilibenzio** [comment]
The same happens to me

Here's the log: 

> {"user_action":"ui error","request":"ACRA report","content_language":"it-IT","content_country":"IT","app_language":"it_IT","service":"none","package":"org.schabi.newpipe","version":"0.21.9","os":"Linux Android 11 - 30","time":"2021-09-18 11:39","exceptions":["java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@29c3f9 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{9843e97 9100:org.schabi.newpipe/u0a189} (pid=9100, uid=10189) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs\n\tat android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)\n\tat android.app.ActivityThread.access$1800(ActivityThread.java:237)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7664)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)\nCaused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{9843e97 9100:org.schabi.newpipe/u0a189} (pid=9100, uid=10189) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs\n\tat android.os.Parcel.createExceptionOrNull(Parcel.java:2373)\n\tat android.os.Parcel.createException(Parcel.java:2357)\n\tat android.os.Parcel.readException(Parcel.java:2340)\n\tat android.os.Parcel.readException(Parcel.java:2282)\n\tat android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5747)\n\tat android.app.ActivityThread.acquireProvider(ActivityThread.java:6820)\n\tat android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2935)\n\tat android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)\n\tat android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)\n\tat android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)\n\tat android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)\n\tat us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)\n\tat org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)\n\tat org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:115)\n\tat android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)\n\t... 8 more\n"],"user_comment":""}

**Comment by Gilibenzio** [comment]
The latest beta (NewPipe v0.21.10_RC3) does not fix the problem. 
There is still the same problem as v0.21.9.

**Comment by LigH-de** [comment]
Google exports subscriptions now only as CSV, not as JSON.

**Comment by highvortex** [comment]
Thanks @LigH-de , this is working. But the xml file exported from Invidious is not working.

**Comment by gloomytree** [comment]
I've just installed the latest update and imports now work again with .csv files. Ty for the work!

**Comment by highvortex** [comment]
Mod Edit:
Fixed in the new update [v0.21.10](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.10) via [Release Candidate v0.21.10](https://github.com/TeamNewPipe/NewPipe/issues/7066)
Closing issue.
Thanks for the work devs!!
