### ISSUE TITLE
Videos on a channel loop

### ISSUE THREAD

**Issue by Poomex** [TeamNewPipe/NewPipe#742]
Hi, since installing 0.10.0, when scrolling through the videos on a channel they start looping after the second page. This means that it's impossible to view videos older than the 60 latest ones on any channel.

**Comment by wb9688** [comment]
Confirmed. @mauriciocolli: Could you take a look at this?

**Comment by mauriciocolli** [comment]
Fixed in [`1df3f67`](https://github.com/TeamNewPipe/NewPipeExtractor/commit/1df3f67074b397902273f903cef05f05d473e088).

**Comment by theScrabi** [comment]
Is dev stable enough so we can merge it into master and release that fix?

**Comment by Poomex** [comment]
Problem is back in 0.11.4. It seems there are more bugs in each subsequent update :(

**Comment by speednroll** [comment]
@Poomex but @mauriciocoli said that he has solved the problem, we just have to wait for the next release. the 0.11.5

**Comment by speednroll** [comment]
@poomex you can see it in #968

**Comment by Poomex** [comment]
Ok, in that case, sorry. Waiting for the update.
