### ISSUE TITLE
Application Crash when playing background playlist

### ISSUE THREAD

**Issue by LeducBastien** [TeamNewPipe/NewPipe#7537]
### Checklist

- [x] I am using the latest version - 0.21.14
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
- Open any playlist on YouTube
- Press play in background 

### Actual behavior
Upon pressing the button, the application crashes. 

### Expected behavior
Upon pressing the button, the button should not crash and play the playlist. 

### Screenshots/Screen recordings
N/A

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.14
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.extractor.stream.StreamInfo org.schabi.newpipe.player.resolver.MediaSourceTag.getMetadata()' on a null object reference
	at org.schabi.newpipe.player.Player.onPlayerError(Player.java:2526)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$10(ExoPlayerImpl.java:1269)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$-K5msfvAakBrxKAsG9AjoK30L1g(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda7.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
	at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$NbKDn9xtItiyMgYZmjIx_Sv1FFQ(Unknown Source:0)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1340)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1175)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:216)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda22.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```
</details>
<hr>

**Comment by TiA4f8R** [comment]
Should have been fixed by #7482. Please comment if that's not the case and I will reopen this issue. Thank you.

**Comment by LeducBastien** [comment]
The bug is still there, but I managed to how EXACTLY why :
The background player crashes when the first video of a playlist is not available (Hidden, Downed, blocked in your country, copystriked...) for whatever reason.

If the playlist is manually started to any video that is available, the bug does not occur.

**Comment by opusforlife2** [comment]
@LeducBastien If this is still happening in the APK you got from #7482, then please add your comment there.

**Comment by teedeey** [comment]
Still happens in 0.21.16, exact same logs, only with peertube though. When i exit the newpipe app since i want audio to play in background it crashes but doesn't give me a log. Clicking on 'popup' button in the peertube video gave me this exact crash log tho

**Comment by opusforlife2** [comment]
@teedeey Please open a new issue so that you're the OP there.
