### ISSUE TITLE
Crash when changing video on Polytron AndroidTV

### ISSUE THREAD

**Issue by iMazariuz** [TeamNewPipe/NewPipe#8384]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Watch any video
2. Click to another video
3. Crash

### Expected behavior

I expect to watch another video normally.

### Actual behavior

It crashed.

### Screenshots/Screen recordings

Since I'm unable to click any buttons on the crash log screen, I posted a video (not a photo because the whole crash log doesn't fit in one screen). 

https://drive.google.com/file/d/1fvCDcQs-_LgA669_9RT1n9-Lgw6eAmKa/view?usp=drivesdk

### Affected Android/Custom ROM version

Linux Android 9-28

### Affected device model

Polytron 2K AI Smart TV

### Additional information

The affected device is a TV

**Comment by Redirion** [comment]
looks like a quick workaround would be to check if `player.getContext()` returns null and then drop out of the method.

**Comment by dolorosus** [comment]
Just for records: Same happens on Philips Android TVs

**Comment by gwilherm** [comment]
Also happens to me on my old Android 6.0 phone:
Here is the report:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 6.0 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@db86ddd with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3237)
	at android.app.ActivityThread.-wrap17(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1597)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3220)
	... 8 more

```
</details>
<hr>

**Comment by Se3ri0us** [comment]
Same happens to me on my Philips 55OLED806 TV with Android 10:
![IMG_20220530_080347](https://user-images.githubusercontent.com/16862614/170927831-ce2c74b2-e1be-4148-a8a7-6be4e78a6c83.jpg)
![IMG_20220530_080359](https://user-images.githubusercontent.com/16862614/170927871-5acdb669-fe66-4a77-bc17-75fcd4861c8a.jpg)

**Comment by mak-42** [comment]
I have same problem on Xiaomi TV:

* __Version:__ 0.23.0
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@559058b with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
	at android.app.ActivityThread.access$1600(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
	... 8 more

```
</details>
<hr>

**Comment by dolorosus** [comment]
FireTV also affected, even with V23.1 

![ftv](https://user-images.githubusercontent.com/11487796/177366632-29a4d7f3-fe45-4037-8337-c573cbc2a0a3.jpg)

**Comment by g4570n** [comment]
I'm having the same issue on a TCL Tv with Android 9.

**Comment by dolorosus** [comment]
Bug persist even in 0.23.2:
Till now it could be circumvented by using 0.22, but that's not possible anymore. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@ebcb3b6 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
	at android.app.ActivityThread.access$1600(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
	... 8 more

```
</details>
<hr>

**Comment by TheFloatingBrain** [comment]
# Logs
```
{"user_action":"requested stream","request":"[https://www.youtube.com/watch?v=s3L2rE39pCc","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.23.1","os":"Linux](https://www.youtube.com/watch?v=s3L2rE39pCc%22,%22content_language%22:%22en-US%22,%22content_country%22:%22US%22,%22app_language%22:%22en_US%22,%22service%22:%22YouTube%22,%22package%22:%22org.schabi.newpipe%22,%22version%22:%220.23.1%22,%22os%22:%22Linux) Android 9 - 28","time":"2022-08-15 01:01","exceptions":["org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\n"],"user_comment":""}
```
# Affected Android/Custom ROM version
```
Andriod 9 (Kernel Version 4.9.125 March 5th 2021) Build BRAVIA_ATV3_4k_UC-user 9 PTT1.190515.001.S43671651
```
# Affected device model
```
Sony Smart TV Bravia Android TV
```

Same issue, just fought with it for a few hours

**Comment by andyrtr** [comment]
0.23.2 fails for me as well on a Sony BraviaTV running Android 9.

**Comment by develsites** [comment]
Latest 0.24.0 fails for me as well also on Android TV 9.0 (AOSP) 

- User Action: ui error
- Request: ACRA report
- Content Language: uk_UA
- Content Country: UA
- App Language: uk_UA
- Service: none
- Version: 0.24.0
- OS: Linux Android 9 - 28

**Comment by dolorosus** [comment]
V24.0 is even worse, try to switch to fullscreen mode...

It hurts to see an essential software going south, but  hope dies last...

**Comment by develsites** [comment]
> V24.0 is even worse, try to switch to fullscreen mode

It happens while the previous video is playing in background. To avoid it I need to close the current playing video before choosing the next video from the list

**Comment by marcostux06** [comment]
> It happens while the previous video is playing in background. To avoid it I need to close the current playing video before choosing the next video from the list
That's right, it becomes almost unusable, I hope they can fix this soon it's the best client program to watch youtube!

**Comment by txret** [comment]
I have the same crashes on Android TV 10/sep 2022 patch level since a few versions back up to and including v0.25, i.e. NewPipe crashes when selecting a video directly from the "Next"/"Queue", however it works fine on Android tablets and phones. Crash log:
``` json
{
    "user_action": "ui error",
    "request": "ACRA report",
    "content_language": "en-US",
    "content_country": "US",
    "app_language": "en_US",
    "service": "none",
    "package": "org.schabi.newpipe",
    "version": "0.25.0",
    "os": "Linux Android 10 - 29",
    "time": "2023-02-12 11:27",
    "exceptions":
    [
        "java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.PlayerService@cdb9b83 with Intent { cmp=org.schabi.newpipe/.player.PlayerService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.Player.handleIntent(android.content.Intent)' on a null object reference\n\tat android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)\n\tat android.app.ActivityThread.access$1800(ActivityThread.java:219)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)\n\tat android.os.Handler.dispatchMessage(Handler.java:107)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.app.ActivityThread.main(ActivityThread.java:7356)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.Player.handleIntent(android.content.Intent)' on a null object reference\n\tat org.schabi.newpipe.player.PlayerService.onStartCommand(PlayerService.java:76)\n\tat android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)\n\t... 8 more\n"
    ],
    "user_comment": ""
}
```

I haven't dug into the NewPipe code to understand why `PlayerService.player` is null at this point (I wild guess is that `PlayerService.cleanup()` is called somewhere prior to the call to `PlayerService.onStartCommand()`, but that is just a guess). I understand that the correct fix would be to find out why `PlayerService.player` is null, not a quick fix with a null check and new instance. However, for any users interested here is a quick fix in [NewPipe/app/src/main/java/org/schabi/newpipe/player/PlayerService.java](https://github.com/txret/NewPipe/blob/1bed7646aecfa82c6d6b0addc56f9c8be5f2b1f3/app/src/main/java/org/schabi/newpipe/player/PlayerService.java#L76) that works for me (also uploaded an [APK](https://github.com/txret/NewPipe/releases/tag/v0.25.0-AndroidTV) - but don't blame me if your TV explodes):
```
    @Override
    public int onStartCommand(final Intent intent, final int flags, final int startId) {
        if (DEBUG) {
            Log.d(TAG, "onStartCommand() called with: intent = [" + intent
                    + "], flags = [" + flags + "], startId = [" + startId + "]");
        }

        if (Intent.ACTION_MEDIA_BUTTON.equals(intent.getAction())
                && player.getPlayQueue() == null) {
            // No need to process media button's actions if the player is not working, otherwise the
            // player service would strangely start with nothing to play
            return START_NOT_STICKY;
        }

        // null check
        if (player == null) {
            player = new Player(this);
        }
        player.handleIntent(intent);
        player.UIs().get(MediaSessionPlayerUi.class)
                .ifPresent(ui -> ui.handleMediaButtonIntent(intent));

        return START_NOT_STICKY;
    }
```

**Comment by AudricV** [comment]
I added this null check in #9592, as it was also reproducible on Android Auto.

Could you try the debug APK and see the issue has been fixed? Thank you in advance.

**Comment by txret** [comment]
> Could you try the debug APK and see the issue has been fixed? Thank you in advance.

Not sure which APK is the "debug APK" but using 0.25.2 from the release page on AndroidTV autoplays the queue and allows selection of an item in the queue correctly (i.e. doesn't crash) so from my perspective the issue seems to be fixed.

Cheers

**Comment by g4570n** [comment]
I have updated to the latest version of the apk (0.25.2) and I still have the same problem, and now also when I want to start the fullscreen playback of a video, it fails and ends the playback.
