### ISSUE TITLE
No resume playback after screen lock or few minute pause

### ISSUE THREAD

**Issue by Salmon-of-knowledge** [TeamNewPipe/NewPipe#8583]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0 after android OS update on OnePlus nord

### Steps to reproduce the bug

Pause or minimize newpipe (screen lock or not). When trying to resume playback tapping play icon flashes white to show detected keypress but nothing happens.

Only workaround is to close the video altogether and reopen which resumes from last position. This does not work for private linked YT videos and reverts to beginning of video instead of resuming.

### Expected behavior

Clicking play icon should resume playback from where it left off.

### Actual behavior

No playback. Have to close out of the video completely, back to the subscription playlist and reselect the video to resume.

### Affected Android/Custom ROM version

Android 12 stock image

### Affected device model

OnePlus Nord

### Additional information

Worked as normal before OS update to Android 12.

**Comment by PrzemekSkw** [comment]
The same bug. 
Android 12
One Plus 9 pro.

Regards.

**Comment by hehhehheh** [comment]
I'm also experiencing a similar problem on OnePlus Nord 2 after upgrading to Android 12.

**Comment by mhmdanas** [comment]
Anybody able to reproduce this on any non-OnePlus devices?

**Comment by notjedi** [comment]
i was experiencing the same issue while using Android 12, but it doesn't happen now as i switched my ROM (running Android 11).

**Comment by mhmdanas** [comment]
@notjedi device?

**Comment by zendynar** [comment]
Hello, I have the same issue on Oneplus 9 pro, Android 12. I see some other issues opened with the same bug, particularly #8294, #8572, there people have issues with other devices as well

**Comment by notjedi** [comment]
@mhmdanas Poco M2 Pro

**Comment by opusforlife2** [comment]
Wasn't there a workaround posted in one of the issues regarding changing something in notification settings?

**Comment by zendynar** [comment]
@opusforlife2 could you send a link to that issue?

**Comment by opusforlife2** [comment]
If I remembered it I would have linked it directly. 😅 It's also possible that it was a workaround for a completely different issue.

**Comment by zendynar** [comment]
@opusforlife2 I think I found [that workaround](https://github.com/TeamNewPipe/NewPipe/issues/5730#issuecomment-1146846109) , at least this works well for me for the time being:
>Another workaround is to switch to the next video, wait for the next video to play, and then switch back to the original one. By doing this, no cache cleaning is required nor progress is lost, and it can play the next video normally

Except here we don't play the "next video" but the original one that is now stuck

**Comment by E0697** [comment]
Facing the same issue on a Realme phone, Android 12.

**Comment by MarcellHarmaci** [comment]
Same issue keeps happening to me.
Happened on both Android 11 and 12. 
Using OnePlus Nord 2

To me it seems like instead of reverting to the beginning, it jumps to the end of the video and you can't restart it without closing and opening the player again.

**Comment by hehhehheh** [comment]
Seems to have resolved itself for OnePlus Nord 2 5G in the OxygenOS 12.1 update with build number DN2103_11_C.10.

**Comment by MarcellHarmaci** [comment]
It is more rare now, but still occurs for me on the same updated OxigenOS build.

**Comment by PrzemekSkw** [comment]
I move to LibreTube and it's very rare there but also sometimes occur.

**Comment by zendynar** [comment]
With the latest 0.24.0 the issue behavior has changed. Before the update it would also sometimes jump to the end of the video and you have to kill and restart the app or the video would start over after resume. Now with the update to 0.24.0 the video can sometimes get stuck but now after app relaunch it continues from the correct timing.

**Comment by opusforlife2** [comment]
> app relaunch 

What, exactly? It can't be swiping it away from Recents, for example, because that would reload the entire content from scratch.

**Comment by funky123** [comment]
I have similar issue. Motorola G100, Android 12.
Most annoying is, if you have a playlist and stop watching waiting some time (mostly over 5 minutes) then try resume the video ist Just stuck.

The workaround for me is to change video resolution, but then new pipe starts playing the first video of my playlist an i always have to Skip videos till the last video I was watching.

Hope this is the right issue if not please give me a hint and I make my own thread.

**Comment by funky123** [comment]
> @funky123 Does your case involve screen locking at all? If not, then yes, it's off-topic here.

i tried it, it seems to appear even without lock screen. then i have to post a seperat issue, right?

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?

**Comment by Salmon-of-knowledge** [comment]
No. Seems to have been fixed. I also changed to a new phone since (nord 2)
so maybe that has addressed the issue with my older install.

**Comment by MarcellHarmaci** [comment]
I would rather reopen this issue, because I am still experiencing this bug. After the video being paused for a while, the play button appears on the player, but when trying to continue with it, the player jumps to the beginning of the video instead.
- Device: OnePlus Nord 2
- Android: 13
- OxygenOS build: DN2103_11_F.50

**Comment by GfEW** [comment]
> Could you open a new issue? Thanks.

@MarcellHarmaci 
Could you also link the new issue here? Because this one is prominently showing up.
