### ISSUE TITLE
"Sorry, something went wrong"

### ISSUE THREAD

**Issue by Toodles919** [TeamNewPipe/NewPipe#8828]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

Just attempting to play any video causes the error.

### Expected behavior

I expect the video to actually play.

### Actual behavior

No videos can play, no matter what I do.  It simply gives me an error message saying "Sorry, something went wrong".

### Screenshots/Screen recordings

<img alt="Screenshot_20220817-145037" src="https://user-images.githubusercontent.com/111461362/185232672-46e9a946-544c-49ce-9c5b-dac69358a165.png" height=600 />

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=fqq9TSkSe2U
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux motorola/river/river:10/QPU30.52-23-13/17fae6:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10

### Affected device model

Moto G7 

### Additional information

Not sure if this helps, but this is an old phone I am using which no longer has a SIM card in it.  Just using wifi.  I have no way of updating my device to the latest version of Android, at least that I know of.

I have uninstalled and reinstalled Newpipe multiple times, but this has not worked either.  I am new to this Github thing and have never reported anything before, so lmk if I'm doing anything wrong here.

**Comment by Toodles919** [comment]
![Uploading Screenshot_20220817-145026.png…]()

**Comment by bell-kevin** [comment]
I'm getting this same issue.

**Comment by bell-kevin** [comment]
![Screenshot_20220817-143127](https://user-images.githubusercontent.com/8269880/185237524-7bb25a23-8497-4f17-8fa9-380d1f402002.png)

**Comment by TobiGr** [comment]
this is fixed in the latest version

**Comment by Toodles919** [comment]
That's a negative Tobi, it's still not cooperating.  Even uninstalled and reinstalled newest version just to be sure.

**Comment by AudricV** [comment]
> Even uninstalled and reinstalled newest version just to be sure.

> - [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

Open the page provided in the template and also read the README, section `Installation and updates`: https://github.com/TeamNewPipe/NewPipe#installation-and-updates.

Follow properly the template instructions the next time you want to open an issue. Thank you.

**Comment by bell-kevin** [comment]
Whatever my problem was, newPipe seems to be working for me again now. Thank you everyone!

**Comment by Toodles919** [comment]
> > Even uninstalled and reinstalled newest version just to be sure.
> 
> > * [x]  I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
> 
> Open the page provided in the template and also read the README, section `Installation and updates`: https://github.com/TeamNewPipe/NewPipe#installation-and-updates.
> 
> Follow properly the template instructions the next time you want to open an issue. Thank you.

I did.  I have the newest version, and the bug continues to affect me.  What am I doing wrong?

**Comment by opusforlife2** [comment]
@Toodles919 The bug report you provided is from the broken version. You need to prove to us that you're on the latest version. Paste a screenshot of your app's About page.

**Comment by Toodles919** [comment]
> @Toodles919 The bug report you provided is from the broken version. You need to prove to us that you're on the latest version. Paste a screenshot of your app's About page.

Oh....jeez.  So, it turns out, what I thought was the new version was still indeed the broken version.  This is because F-Droid did not make the update available to me until today.  I don't know why everybody else got the update several days ago and I didn't until now.  Maybe my old phone has something to do with it.

Either way, sorry to waste your time people.

**Comment by opusforlife2** [comment]
@Toodles919 https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

**Comment by bell-kevin** [comment]
I upgraded to Android 13. That may have solved my problem, but I'm not sure.
