### ISSUE TITLE
[YouTube] Some formats and resolutions buffer very frequently

### ISSUE THREAD

**Issue by Eiion** [TeamNewPipe/NewPipe#8839]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Select video
2. See it play for a few seconds until it starts buffering like half a minute, then play for another few seconds only to buffer again like forever.
3. Play a few seconds, buffer forever repeats until the end of the video

### Expected behavior

Tap on video and be able to watch it in one go opposed to getting buffering pauses for a multiple of the video's actual length. 

### Actual behavior

Bufferin videos over and over and over and over - no matter which one. 

### Affected device model

Toolboxed fire hd 10 plus tablet

### Additional information

While videos play perfectly fine with the YouTube app NewPipe currently is unusable due to the issue described above.

**Comment by PrinceRaj53** [comment]
Experiencing the same issue. This is happening frequently nowadays. 

Although force closing the app, clearing cache & restarting it 3-4 times fixes the issue sometimes, but not always. Do try this and see if it works.

**Comment by nikhilCad** [comment]
For me 720p buffers but if I change default to 1080p it doesn't buffer

**Comment by AudricV** [comment]
Like I said on the [Reddit 0.23.2 release post](https://www.reddit.com/r/NewPipe/comments/wnbkqd/release_v0232/ik446vs/):

> - streams which are coming from HTML clients, such as the 720p streams on videos with at least 720p60 streams, streams of age-restricted videos and undownloadable WEBM streams will be throttled/will buffer very frequently if the decryption of the throttling parameter fails again in the future.

The decryption of the throttling parameter is failing again, see TeamNewPipe/NewPipeExtractor#902.

There is nothing you can do about this on non age-restricted videos except using streams which doesn't meet the conditions stated above.

**Comment by Theta-Dev** [comment]
Here I have a debug build which fixes the issue.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9387139/app-debug.zip)

**Comment by Eiion** [comment]
No idea if it's related to the issue I've posted above but after changing video resolution to 1080p60 in order to have videos play again they now stutter like crazy. It wasn't ever an issue before but now it is. (And it also makes me wonder why there's not an option to select to standard 1080p30 anymore 🤔)

**Comment by opusforlife2** [comment]
> Here I have a debug build which fixes the issue.

Your debug build [works, works, works, works, works, works, works](https://piped.kavin.rocks/watch?v=5GL9JoH4Sws). 🎉

**Comment by TAXSET** [comment]
Having the same issue, @Theta-Dev debug build works perfectly.

**Comment by eladkarako** [comment]
throttling probably,  
due to js player signature extraction failure?  
3-10KB/s is not enough for filling up buffers,  
and okhttp is set to be too eager draining them anyway.  
[cronet time yet?](https://maven.google.com/web/index.html?q=cronet)

**Comment by opusforlife2** [comment]
Should be fixed by 0.23.3. Comment if not.

**Comment by Eiion** [comment]
This issue should be re-opened as the problem is back just like before since yesterday.

**Comment by eladkarako** [comment]
it is time to <strong>finally</strong> incorporate cronet.  
PROPER buffering and QUIC+brotli with YouTube servers  
works with existing code of okhttp.  
embedded version does not requires Google Framework.  
for as little as additional 5MB overall.  
that's a good tradeoff.

<a href="https://maven.google.com/web/index.html?q=cron"><img src="https://user-images.githubusercontent.com/415238/188068971-69ac8331-54cf-4d8c-816a-1a416454f80b.png" /></a>

**Comment by eladkarako** [comment]
would you accept pr with cronet?

**Comment by AudricV** [comment]
HTTP/3 with QUIC will not solve this issue, as you would be still throttled. Using Cronet with QUIC enabled would allow YouTube to track NewPipe users with the QUIC User-Agent ID (which is not the `User-Agent` HTTP header) sent by Cronet (containing the package ID and version), which cannot be set or edited by apps, at least easily: see https://github.com/TeamNewPipe/NewPipe/issues/5352#issuecomment-1214337010.

The only fix is to make the throttling parameter decryption work again.

**Comment by eladkarako** [comment]
cronet by itself w/o brotli/QUIC has a superb cache handling.  
it sits lower than okhttp and smooths-out everything.

users may fine tune it though settings:  
  amount of cache in RAM, amount of cache in disk (default 32MB).  
  switch on brotli (default off).  
  switch on QUIC (default off).  
  switch off cronet net-stack entirely (default off)
through settings.

the jsplayer signature-function decryption is needed regardless,  
there is very little to do with a bandwidth of 5kb/s.

**Comment by AudricV** [comment]
This issue should be fixed in the next update with TeamNewPipe/NewPipeExtractor#925.

**Comment by AudricV** [comment]
Closing, as the issue should have been fixed, for real this time, with TeamNewPipe/NewPipeExtractor#905 and TeamNewPipe/NewPipeExtractor#934, shipped with 0.24.0.

**Comment by vehosah** [comment]
> Closing, as the issue should have been fixed, for real this time, with [TeamNewPipe/NewPipeExtractor#905](https://github.com/TeamNewPipe/NewPipeExtractor/pull/905) and [TeamNewPipe/NewPipeExtractor#934](https://github.com/TeamNewPipe/NewPipeExtractor/pull/934), shipped with 0.24.0.

Umm unfortunately it keeps buffering on me, no matter if I have 0.25.2 or 0.26.0
