### ISSUE TITLE
download not work

### ISSUE THREAD

**Issue by Suburbanno** [TeamNewPipe/NewPipe#912]
```
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "pt",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.11.1",
   "os": "Linux Android 5.1.1 - 22",
   "time": "2017-12-09 16:05",
   "ip_range": "170.238.0.0",
   "exceptions": [
      "java.lang.RuntimeException: java.io.IOException: open failed: EACCES (Permission denied)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:350)\nCaused by: java.io.IOException: open failed: EACCES (Permission denied)\n\tat java.io.File.createNewFile(File.java:944)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\nCaused by: android.system.ErrnoException: open failed: EACCES (Permission denied)\n\tat libcore.io.Posix.open(Native Method)\n\tat libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)\n\tat java.io.File.createNewFile(File.java:937)\n\t... 1 more\njava.io.IOException: open failed: EACCES (Permission denied)\n\tat java.io.File.createNewFile(File.java:944)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\nCaused by: android.system.ErrnoException: open failed: EACCES (Permission denied)\n\tat libcore.io.Posix.open(Native Method)\n\tat libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)\n\tat java.io.File.createNewFile(File.java:937)\n\t... 1 more\nandroid.system.ErrnoException: open failed: EACCES (Permission denied)\n\tat libcore.io.Posix.open(Native Method)\n\tat libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)\n\tat java.io.File.createNewFile(File.java:937)\n\tat us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:342)\n"
   ],
   "user_comment": ""
}
```

**Comment by wb9688** [comment]
Do you try to download to a SD card? If so, that doesn't work yet. If not,
are you sure you've given NewPipe the correct permission (Settings -> Apps
-> NewPipe -> Permissions -> Storage iirc)?

**Comment by berserkwarwolf** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "en",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.11.0",
   "os": "Linux Android 8.1.0 - 27",
   "time": "2017-12-15 13:41",
   "ip_range": "181.117.0.0",
   "exceptions": [
      "java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)\n\tat android.app.ActivityThread.-wrap4(Unknown Source:0)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6494)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\nCaused by: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:103)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)\n\t... 8 more\njava.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:103)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)\n\tat android.app.ActivityThread.-wrap4(Unknown Source:0)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6494)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\n"
   ],
   "user_comment": ""
}

**Comment by wb9688** [comment]
@berserkwarwolf: That's a different issue and has been fixed in the latest
version.

**Comment by berserkwarwolf** [comment]
@wb9688 is it pushed to F-Droid ? also, which build / version are we talking about exactly ?

**Comment by berserkwarwolf** [comment]
@wb9688 I'm on Android 8.1.0, NewPipe v 0.11.0, and still getting this error.

**Comment by wb9688** [comment]
@berserkwarwolf: It happens only on Android Oreo and is fixed in v0.11.1,
which isn't on F-Droid yet.

**Comment by TobiGr** [comment]
version 0.11.1 is the latest version.  You can download it from [F-Droid](https://f-droid.org/packages/org.schabi.newpipe/).

**Comment by Futureknows** [comment]
I noticed the same issue  with .0.14.1. Files download and complete but when attempting to play `"error opening file"`. Permissions are granted. I can see the files (m4a, mp4s) in file browsers and they are the right size but no player will play them (bsplayer, vlc, etc).
